import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { MinistryIntelligenceData, ResearchResource } from "@/lib/daily-intelligence/types";
import type { ActiveTask, MinistryEvent, User } from "@/lib/types";

const mocks = vi.hoisted(() => ({
  loadResearchQueueForDay: vi.fn(),
  runWeeklyResearchSweep: vi.fn(),
  sendDailyBriefToSlack: vi.fn()
}));

vi.mock("@/lib/daily-intelligence/firecrawl-research", () => ({
  loadResearchQueueForDay: mocks.loadResearchQueueForDay,
  runWeeklyResearchSweep: mocks.runWeeklyResearchSweep
}));

vi.mock("@/lib/daily-intelligence/source", () => ({
  getMinistryIntelligenceData: vi.fn(async () => data())
}));

vi.mock("@/lib/daily-intelligence/slack", async () => {
  const actual = await vi.importActual<typeof import("@/lib/daily-intelligence/slack")>("@/lib/daily-intelligence/slack");
  return {
    ...actual,
    sendDailyBriefToSlack: mocks.sendDailyBriefToSlack
  };
});

import { POST } from "@/app/api/daily-intelligence/brief/route";

const secret = "test-secret";

function user(overrides: Partial<User> = {}): User {
  return {
    id: "usr_admin",
    firstName: "Andrew",
    lastName: "Bostwick",
    email: "andrew@example.com",
    role: "admin",
    ...overrides
  };
}

function event(overrides: Partial<MinistryEvent> = {}): MinistryEvent {
  return {
    id: "evt_midweek",
    title: "Midweek Gathering",
    description: "Worship, teaching, and small groups.",
    type: "weekly",
    startTime: "2026-07-16T18:00:00.000Z",
    endTime: "2026-07-16T20:00:00.000Z",
    status: "planning",
    location: "Student Center",
    budgetTarget: 500,
    budgetActual: 0,
    volunteersNeeded: 4,
    contactOwnerId: "usr_admin",
    autoGeneratedTimeline: [],
    createdAt: "2026-07-01T12:00:00.000Z",
    ...overrides
  };
}

function task(overrides: Partial<ActiveTask> = {}): ActiveTask {
  return {
    id: "task_setup",
    eventId: "evt_midweek",
    taskTitle: "Confirm worship set",
    dueDate: "2026-07-16T12:00:00.000Z",
    assignedUserId: "usr_admin",
    status: "todo",
    autoGenerated: true,
    timelineOffsetDays: -2,
    ...overrides
  };
}

function data(overrides: Partial<MinistryIntelligenceData> = {}): MinistryIntelligenceData {
  return {
    ministryId: "00000000-0000-4000-8000-000000000001",
    events: [event()],
    tasks: [task()],
    users: [user()],
    expenses: [],
    communications: [],
    integrationLogs: [],
    activity: [],
    ...overrides
  };
}

function resource(overrides: Partial<ResearchResource> = {}): ResearchResource {
  return {
    id: "res_student_culture",
    day: "thursday",
    topic: "Student Culture",
    type: "article",
    title: "Teen Culture Brief",
    url: "https://example.com/student-culture",
    source: "example.com",
    summary: "A pastoral awareness resource for teen culture.",
    whyIncluded: "Fits Thursday's student culture rhythm.",
    score: 12,
    ...overrides
  };
}

describe("daily intelligence brief route", () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-16T12:00:00.000Z")); // Thursday
    process.env.DAILY_BRIEFING_CRON_SECRET = secret;
    mocks.loadResearchQueueForDay.mockResolvedValue([]);
    mocks.runWeeklyResearchSweep.mockResolvedValue({ resources: [resource(), resource({ id: "res_monday", day: "monday" })], warnings: [] });
    mocks.sendDailyBriefToSlack.mockResolvedValue(undefined);
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.clearAllMocks();
    delete process.env.DAILY_BRIEFING_CRON_SECRET;
  });

  it("runs the weekly Firecrawl sweep out of cycle when forced", async () => {
    const response = await POST(
      new Request("https://leademergence.com/api/daily-intelligence/brief?researchSweep=force", {
        method: "POST",
        headers: { authorization: `Bearer ${secret}` }
      })
    );
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(mocks.runWeeklyResearchSweep).toHaveBeenCalledWith({
      ministryId: "00000000-0000-4000-8000-000000000001",
      weekStart: "2026-07-13"
    });
    expect(body.researchSweep).toBe("forced");
    expect(body.preview).toContain("Teen Culture Brief");
    expect(body.preview).not.toContain("res_monday");
  });

  it("keeps Thursday briefs on the cached queue when research is not forced", async () => {
    const response = await POST(
      new Request("https://leademergence.com/api/daily-intelligence/brief", {
        method: "POST",
        headers: { authorization: `Bearer ${secret}` }
      })
    );
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(mocks.runWeeklyResearchSweep).not.toHaveBeenCalled();
    expect(body.researchSweep).toBe("skipped");
  });
});
