import { describe, expect, it } from "vitest";
import { buildDailyIntelligenceBrief } from "@/lib/daily-intelligence/operations";
import { formatDailyIntelligenceSlackMessage } from "@/lib/daily-intelligence/slack";
import type { MinistryIntelligenceData, ResearchResource } from "@/lib/daily-intelligence/types";
import type { ActiveTask, MinistryEvent, User } from "@/lib/types";

const now = new Date("2026-07-14T12:00:00.000Z"); // Tuesday

function user(overrides: Partial<User> = {}): User {
  return {
    id: "usr_admin",
    firstName: "Andrew",
    lastName: "Bostwick",
    email: "andrew@example.com",
    role: "admin",
    ...overrides
  };
}

function event(overrides: Partial<MinistryEvent> = {}): MinistryEvent {
  return {
    id: "evt_midweek",
    title: "Midweek Gathering",
    description: "Worship, teaching, and small groups.",
    type: "weekly",
    startTime: "2026-07-16T18:00:00.000Z",
    endTime: "2026-07-16T20:00:00.000Z",
    status: "planning",
    location: "Student Center",
    budgetTarget: 500,
    budgetActual: 0,
    volunteersNeeded: 4,
    contactOwnerId: "usr_admin",
    autoGeneratedTimeline: [],
    createdAt: "2026-07-01T12:00:00.000Z",
    ...overrides
  };
}

function task(overrides: Partial<ActiveTask> = {}): ActiveTask {
  return {
    id: "task_setup",
    eventId: "evt_midweek",
    taskTitle: "Confirm worship set",
    dueDate: "2026-07-14T12:00:00.000Z",
    assignedUserId: "usr_admin",
    status: "todo",
    autoGenerated: true,
    timelineOffsetDays: -2,
    ...overrides
  };
}

function data(overrides: Partial<MinistryIntelligenceData> = {}): MinistryIntelligenceData {
  return {
    ministryId: "00000000-0000-4000-8000-000000000001",
    events: [event()],
    tasks: [task()],
    users: [user()],
    expenses: [],
    communications: [],
    integrationLogs: [],
    activity: [],
    ...overrides
  };
}

function resource(overrides: Partial<ResearchResource> = {}): ResearchResource {
  return {
    id: "res_game",
    day: "tuesday",
    topic: "Quick Sunday Icebreakers",
    type: "game",
    title: "Circle Question Dash",
    url: "https://example.com/game-demo",
    source: "example.com",
    summary: "Supplies: none. Setup: circle. Instructions: students answer quick prompts.",
    whyIncluded: "Fits a Sunday morning low-setup icebreaker.",
    score: 12,
    ...overrides
  };
}

describe("buildDailyIntelligenceBrief", () => {
  it("prioritizes overdue, missing communication, volunteer, and decision items", () => {
    const brief = buildDailyIntelligenceBrief({
      now,
      data: data({
        tasks: [
          task({ id: "task_overdue", taskTitle: "Confirm worship set", dueDate: "2026-07-13T12:00:00.000Z" }),
          task({ id: "task_blocked", taskTitle: "Print leader guide", status: "blocked", dueDate: "2026-07-15T12:00:00.000Z" })
        ]
      }),
      resources: [resource()]
    });

    expect(brief.sections.needsAttentionToday.map((item) => item.title)).toContain("Confirm worship set");
    expect(brief.sections.needsAttentionToday.map((item) => item.title)).toContain("Print leader guide");
    expect(brief.sections.communications.some((item) => item.why.includes("Missing"))).toBe(true);
    expect(brief.sections.studentVolunteerCare.some((item) => item.why.includes("volunteer"))).toBe(true);
    expect(brief.sections.decisionsNeeded.some((item) => item.why.includes("owner"))).toBe(false);
  });

  it("uses the exact Tuesday game lab structure", () => {
    const brief = buildDailyIntelligenceBrief({
      now,
      data: data(),
      resources: [
        resource({ id: "res_quick_1", title: "Fast Names" }),
        resource({ id: "res_quick_2", title: "Would You Rather Corners" }),
        resource({ id: "res_long", title: "Team Relay Puzzle" })
      ]
    });

    expect(brief.content.title).toBe("Tuesday - Game Lab");
    expect(brief.content.items).toHaveLength(3);
    expect(brief.content.items[0].title).toBe("Fast Names");
    expect(brief.content.items[2].why).toContain("15-45 minutes");
  });

  it("keeps student-care task details out of the Slack message", () => {
    const brief = buildDailyIntelligenceBrief({
      now,
      data: data({
        tasks: [
          task({
            id: "task_student_private",
            taskTitle: "Follow up with Student Jane Doe about anxiety disclosure",
            dueDate: "2026-07-14T12:00:00.000Z"
          })
        ]
      })
    });
    const message = formatDailyIntelligenceSlackMessage(brief);

    expect(brief.sections.studentVolunteerCare.some((item) => item.title === "Student follow-up task needs review")).toBe(true);
    expect(message).not.toContain("Jane Doe");
    expect(message).not.toContain("anxiety disclosure");
    expect(message).toContain("Details stay inside Lead Emerge");
  });
});

