import { describe, expect, it, vi } from "vitest";
import { DailyBriefSlackConfigError, formatDailyIntelligenceSlackMessage, readDailyBriefSlackConfig, sendDailyBriefToSlack } from "@/lib/daily-intelligence/slack";
import { buildDailyIntelligenceBrief } from "@/lib/daily-intelligence/operations";
import type { MinistryIntelligenceData } from "@/lib/daily-intelligence/types";

const configuredEnv = { DAILY_BRIEFING_SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/daily/briefing" };

function response(ok = true, status = 200): Response {
  return { ok, status, json: async () => ({}) } as Response;
}

const data: MinistryIntelligenceData = {
  events: [],
  tasks: [],
  users: [],
  expenses: [],
  communications: [],
  integrationLogs: [],
  activity: []
};

describe("daily intelligence Slack config", () => {
  it("uses a standalone daily briefing webhook variable", () => {
    expect(readDailyBriefSlackConfig({ COMMAND_CENTER_SLACK_WEBHOOK_URL: "wrong" }).configured).toBe(false);
    expect(readDailyBriefSlackConfig(configuredEnv).configured).toBe(true);
  });
});

describe("sendDailyBriefToSlack", () => {
  it("does not post without the daily briefing webhook", async () => {
    const fetchImpl = vi.fn();
    await expect(sendDailyBriefToSlack({ text: "brief", env: {}, fetchImpl })).rejects.toThrow(DailyBriefSlackConfigError);
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it("posts a single Slack message to the configured daily briefing webhook", async () => {
    const fetchImpl = vi.fn().mockResolvedValue(response());
    await sendDailyBriefToSlack({ text: "brief", env: configuredEnv, fetchImpl });
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    expect(JSON.parse((fetchImpl.mock.calls[0][1] as RequestInit).body as string)).toEqual({ text: "brief" });
  });
});

describe("formatDailyIntelligenceSlackMessage", () => {
  it("renders every required daily section label", () => {
    const brief = buildDailyIntelligenceBrief({ data, now: new Date("2026-07-15T12:00:00.000Z") });
    const message = formatDailyIntelligenceSlackMessage(brief);

    expect(message).toContain("🚨 Needs Attention Today");
    expect(message).toContain("📅 Next 7 Days");
    expect(message).toContain("📆 Days 8-14");
    expect(message).toContain("💬 Communications");
    expect(message).toContain("👥 Student & Volunteer Care");
    expect(message).toContain("🎯 Decisions Needed");
    expect(message).toContain("✅ Recent Progress");
    expect(message).toContain("⚙️ System Health");
  });

  it("makes record links absolute when the app URL is configured", () => {
    const brief = buildDailyIntelligenceBrief({
      data: {
        ...data,
        events: [
          {
            id: "evt_1",
            title: "Sunday Gathering",
            description: "Weekly student gathering.",
            type: "small_group_gathering",
            startTime: "2026-07-16T18:00:00.000Z",
            endTime: "2026-07-16T20:00:00.000Z",
            status: "planning",
            location: "Student Center",
            budgetTarget: 100,
            contactOwnerId: "usr_1",
            autoGeneratedTimeline: [],
            createdAt: "2026-07-01T12:00:00.000Z"
          }
        ]
      },
      now: new Date("2026-07-15T12:00:00.000Z")
    });
    const message = formatDailyIntelligenceSlackMessage(brief, { DAILY_BRIEFING_APP_URL: "https://lead.example.test" });
    expect(message).toContain("<https://lead.example.test/events?event=evt_1|Open record>");
  });
});
