/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and kept here so the
// empty workspace has a complete TypeScript scaffold.
