import { describe, expect, it } from "vitest";

import { containsForbiddenKeys } from "@/lib/emma/context";
import { buildSafeEventEmmaContext } from "@/lib/emma/context/event-context";
import type { EventWorkspace, MinistryEvent } from "@/lib/types";

function event(overrides: Partial<MinistryEvent> = {}): MinistryEvent {
  return {
    id: "evt_safe",
    ministryId: "ministry-emerge",
    title: "Winter Retreat",
    description: "A safe planning description for leaders.",
    type: "retreat",
    startTime: "2026-07-10T18:00:00.000Z",
    endTime: "2026-07-12T12:00:00.000Z",
    status: "planning",
    location: "Lakeview Retreat Center",
    targetGroup: "High School",
    volunteersNeeded: 8,
    priority: "high",
    contactOwnerId: "usr_admin",
    autoGeneratedTimeline: [],
    notes: "This internal note must not enter EMMA event context.",
    createdAt: "2026-06-01T00:00:00.000Z",
    ...overrides
  };
}

function workspace(input: MinistryEvent = event()): EventWorkspace {
  return {
    event: input,
    tasks: [
      {
        id: "task_1",
        ministryId: "ministry-emerge",
        eventId: input.id,
        taskTitle: "Confirm lodging",
        dueDate: "2026-07-01T12:00:00.000Z",
        assignedUserId: "usr_admin",
        status: "todo",
        autoGenerated: true,
        timelineOffsetDays: -30,
        notes: "Task note must not enter EMMA context."
      }
    ],
    communications: [],
    integrationLogs: [],
    expenses: [{ id: "exp_1", eventId: input.id, categoryId: "venue", amount: 1500, description: "Deposit", timestamp: input.createdAt }],
    missingInformation: [{ id: "mi_location", area: "communications", label: "Parent pickup details", severity: "recommended" }],
    activity: [{ id: "act_1", type: "event_updated", eventId: input.id, actorId: "usr_admin", message: "Updated event", metadata: {}, timestamp: input.createdAt }]
  };
}

describe("buildSafeEventEmmaContext", () => {
  it("builds a manifest and safe event context from allow-listed event planning fields", () => {
    const result = buildSafeEventEmmaContext(workspace());

    expect(result.contextManifest.entries).toEqual([
      { recordId: "evt_safe", recordType: "event", category: "event", sourceTable: "events" },
      { recordId: "task_1", recordType: "task", category: "task", sourceTable: "tasks" },
      { recordId: "act_1", recordType: "activity_log", category: "activity_log", sourceTable: "activity_logs" },
      { recordId: "exp_1", recordType: "budget_item", category: "budget", sourceTable: "events" }
    ]);
    expect(result.safeEventContext).toMatchObject({
      eventId: "evt_safe",
      title: "Winter Retreat",
      eventType: "retreat",
      location: "Lakeview Retreat Center",
      targetGroup: "High School",
      ownerId: "usr_admin",
      volunteersNeeded: 8,
      missingInformation: ["Parent pickup details"]
    });
    expect(containsForbiddenKeys(result.contextManifest)).toBe(false);
  });

  it("excludes sensitive, private, and note-like fields by default", () => {
    const unsafeEvent = event({
      ...( {
        allergies: "peanuts",
        medical: "private medication detail",
        pastoralCareNotes: "confidential care note",
        parentEmail: "parent@example.test",
        paymentDetails: "card ending 1111",
        waiverPrivateFormDetails: "private form data",
        confidentialLeadershipNotes: "private leader note"
      } as Partial<MinistryEvent>)
    });

    const result = buildSafeEventEmmaContext(workspace(unsafeEvent));
    const serialized = JSON.stringify(result.contextManifest);

    expect(serialized).not.toContain("peanuts");
    expect(serialized).not.toContain("private medication detail");
    expect(serialized).not.toContain("confidential care note");
    expect(serialized).not.toContain("parent@example.test");
    expect(serialized).not.toContain("card ending 1111");
    expect(serialized).not.toContain("private form data");
    expect(serialized).not.toContain("private leader note");
    expect(serialized).not.toContain("This internal note must not enter EMMA event context.");
    expect(containsForbiddenKeys(result.contextManifest)).toBe(false);
  });
});
