import { describe, expect, it } from "vitest";

import { buildLeaderDailyBriefEvidence, formatLeaderDailyBriefMessage } from "@/lib/leader-daily-brief/operations";
import type { MinistryIntelligenceData } from "@/lib/daily-intelligence/types";
import type { ActiveTask, MinistryEvent, User } from "@/lib/types";

function user(overrides: Partial<User> = {}): User {
  return {
    id: "usr_leader",
    firstName: "Maya",
    lastName: "Chen",
    email: "maya@example.com",
    role: "leader",
    ...overrides
  };
}

function event(overrides: Partial<MinistryEvent> = {}): MinistryEvent {
  return {
    id: "evt_sunday",
    title: "Sunday Small Groups",
    description: "Worship and small groups.",
    type: "small_group_gathering",
    startTime: "2026-07-19T14:00:00.000Z",
    endTime: "2026-07-19T15:30:00.000Z",
    status: "planning",
    location: "Student Center",
    targetGroup: "Middle and high school",
    volunteersNeeded: 4,
    autoGeneratedTimeline: [],
    createdAt: "2026-07-01T12:00:00.000Z",
    ...overrides
  };
}

function task(overrides: Partial<ActiveTask> = {}): ActiveTask {
  return {
    id: "task_setup",
    eventId: "evt_sunday",
    taskTitle: "Confirm small group rooms",
    dueDate: "2026-07-18T12:00:00.000Z",
    assignedUserId: "usr_leader",
    status: "todo",
    autoGenerated: true,
    timelineOffsetDays: -1,
    ...overrides
  };
}

function data(overrides: Partial<MinistryIntelligenceData> = {}): MinistryIntelligenceData {
  return {
    ministryId: "00000000-0000-4000-8000-000000000001",
    events: [event()],
    tasks: [task()],
    users: [user()],
    expenses: [],
    communications: [],
    integrationLogs: [],
    activity: [],
    ...overrides
  };
}

describe("leader daily brief operations", () => {
  it("keeps platform evidence volunteer-facing and excludes budget fields", () => {
    const evidence = buildLeaderDailyBriefEvidence({
      data: data({
        events: [event({ budgetTarget: 5000, budgetActual: 4200, notes: "staff-only planning note" })]
      }),
      now: new Date("2026-07-16T23:00:00.000Z")
    });

    expect(JSON.stringify(evidence)).not.toContain("budget");
    expect(JSON.stringify(evidence)).not.toContain("staff-only planning note");
    expect(evidence.upcomingEvents[0]).toMatchObject({ title: "Sunday Small Groups" });
  });

  it("formats the requested GroupMe structure under the bot limit", () => {
    const formatted = formatLeaderDailyBriefMessage({
      whyThisMatters: [
        "This week matters because leader preparation creates space for ordinary conversations to become more intentional discipleship moments."
      ],
      upcoming: ["Sunday Small Groups - Jul 19 at Student Center", "Confirm small group rooms is due Jul 18."],
      prepareForSunday: ["Sermon preparation has not yet been published.", "Facilitation insight: start with one honest observation question."],
      studentsToNotice: "Be intentional to draw quieter students into discussion with patient, low-pressure questions.",
      leaderPractice: "Let silence do some work before you rescue the room.",
      todaysPractice: "Wait five seconds longer after your next question.",
      prayer: "Lord, strengthen our volunteers and make small groups places of honest conversation and patient discipleship."
    });

    expect(formatted.message).toContain("# LEADER DAILY BRIEF");
    expect(formatted.message).toContain("📖 Why This Matters This Week");
    expect(formatted.message).toContain("Today's Practice:");
    expect(formatted.message.length).toBeLessThanOrEqual(1000);
  });
});
