import { describe, expect, it } from "vitest";

import type { AuthSession } from "@/lib/auth/server";
import { runMinistryPageServerChat } from "@/lib/emma/ministry-page-server-chat";

const guestSession: AuthSession = {
  isMock: false,
  isGuest: true,
  guestSessionId: "guest-ai-test",
  user: {
    id: "guest_guest-ai-test",
    email: "guest@example.test",
    fullName: "Guest",
    role: "guest"
  }
};

describe("guest EMMA simulation", () => {
  it("returns stock responses without requiring admin/leader role or provider setup", async () => {
    const result = await runMinistryPageServerChat({
      session: guestSession,
      rawInput: { page: "events", prompt: "What should I do next?" },
      overview: {
        events: [{
          id: "guest_evt",
          title: "Guest Event",
          description: "Fake event.",
          type: "weekly",
          startTime: new Date().toISOString(),
          endTime: new Date().toISOString(),
          status: "planning",
          autoGeneratedTimeline: [],
          createdAt: new Date().toISOString()
        }],
        tasks: [{
          id: "guest_task",
          eventId: "guest_evt",
          taskTitle: "Fake task",
          dueDate: new Date().toISOString(),
          assignedUserId: "guest_leader",
          status: "todo",
          autoGenerated: true,
          timelineOffsetDays: -7
        }],
        users: [],
        expenses: [],
        activity: []
      }
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("guest_simulation");
    expect(result.data.model).toBe("guest-stock-responses");
    expect(result.data.warnings.join(" ")).toMatch(/no external AI call/i);
  });
});
