import { describe, expect, it } from "vitest";

import type { AuthSession } from "@/lib/auth/server";
import { runMinistryPageServerChat } from "@/lib/emma/ministry-page-server-chat";

const guestSession: AuthSession = {
  isMock: false,
  isGuest: true,
  guestSessionId: "guest-ai-test",
  user: {
    id: "guest_guest-ai-test",
    email: "guest@example.test",
    fullName: "Guest",
    role: "guest"
  }
};

describe("guest EMMA demo responses", () => {
  it("returns read-only demo responses without requiring admin/leader role or provider setup", async () => {
    const result = await runMinistryPageServerChat({
      session: guestSession,
      rawInput: { page: "events", prompt: "What should I do next?" },
      overview: {
        events: [{
          id: "guest_evt",
          title: "Guest Event",
          description: "Demo event.",
          type: "small_group_gathering",
          startTime: new Date().toISOString(),
          endTime: new Date().toISOString(),
          status: "planning",
          autoGeneratedTimeline: [],
          createdAt: new Date().toISOString()
        }],
        tasks: [{
          id: "guest_task",
          eventId: "guest_evt",
          taskTitle: "Demo task",
          dueDate: new Date().toISOString(),
          assignedUserId: "guest_leader",
          status: "todo",
          autoGenerated: true,
          timelineOffsetDays: -7
        }],
        users: [],
        expenses: [],
        activity: []
      }
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("guest_simulation");
    expect(result.data.model).toBe("guest-stock-responses");
    expect(result.data.warnings.join(" ")).toMatch(/no external AI call/i);
  });

  it("resolves only the selected canonical narrative without creating a proposal or write", async () => {
    const result = await runMinistryPageServerChat({
      session: guestSession,
      rawInput: {
        page: "dashboard",
        prompt: "What should leadership discuss?",
        selectedGuestNarrativeId: "small-group-growth",
        createProposal: true
      },
      overview: {
        events: [],
        tasks: [],
        users: [],
        expenses: [],
        activity: []
      }
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.response.summary).toContain("MS 6th Grade North grew from 10 to 16 students");
    expect(JSON.stringify(result.data.response)).toContain("10 → 11 → 12 → 13 → 14 → 15 → 16");
    expect(JSON.stringify(result.data.response)).not.toContain("Mason Bridge");
    expect(JSON.stringify(result.data.response)).not.toContain("Sunday participation fell");
    expect(result.data.proposalCreated).toBe(false);
    expect(result.data.proposalId).toBeNull();
    expect(result.data.executed).toBe(false);
    expect(result.data.provider).toBe("deterministic");
    expect(result.data.warnings.join(" ")).toMatch(/no external AI call|no writes/i);
  });
});
