import { describe, expect, it, vi } from "vitest";

import {
  answerMinistryEmmaPrompt,
  selectDefaultEmmaEvent,
  shouldRunAuditedEventSummary,
  type MinistryEmmaOverview
} from "@/lib/emma/ministry-page-assistant";
import type { ActiveTask, ActivityLog, EventExpense, MinistryEvent, User } from "@/lib/types";

vi.mock("@/lib/utils", async () => {
  const actual = await vi.importActual<typeof import("@/lib/utils")>("@/lib/utils");
  return {
    ...actual,
    money: (value: number) => `$${value.toFixed(0)}`
  };
});

describe("ministry page EMMA assistant", () => {
  it("answers communication prompts with missing field guidance and preview boundaries", () => {
    const response = answerMinistryEmmaPrompt({
      overview: makeOverview(),
      page: "communications",
      prompt: "Which drafts need review?"
    });

    expect(response.summary).toContain("need communication review");
    expect(response.points).toContain("Winter Retreat needs location, audience, owner.");
    expect(response.points).toContain("Email, text, and GroupMe outputs stay behind human approval gates.");
  });

  it("answers budget prompts with event target and spend risk", () => {
    const response = answerMinistryEmmaPrompt({
      overview: makeOverview(),
      page: "budget",
      prompt: "Where are budget risks?"
    });

    expect(response.summary).toContain("$450 recorded against $300");
    expect(response.points).toContain("Recorded spend is $150 over target.");
    expect(response.nextActions).toContain("Keep accounting integrations stubbed until approved.");
  });

  it("uses static page guidance when no ministry overview is available", () => {
    const response = answerMinistryEmmaPrompt({
      page: "files",
      prompt: "What file areas are planned?",
      staticSignals: ["Drive folder creation is preview-only."]
    });

    expect(response.summary).toBe("EMMA is available for files planning support.");
    expect(response.points).toEqual(["Drive folder creation is preview-only."]);
  });

  it("selects the next upcoming event for audited summaries", () => {
    const event = selectDefaultEmmaEvent(makeOverview().events);
    expect(event?.title).toBe("Winter Retreat");
  });

  it("detects prompts that should use the audited event summary route", () => {
    expect(shouldRunAuditedEventSummary("Summarize selected event")).toBe(true);
    expect(shouldRunAuditedEventSummary("Which tasks need follow-up?")).toBe(false);
  });
});

function makeOverview(): MinistryEmmaOverview {
  const users: User[] = [
    {
      id: "usr_admin",
      email: "admin@example.com",
      firstName: "Alex",
      lastName: "Walker",
      role: "admin"
    } as User
  ];
  const events: MinistryEvent[] = [
    {
      id: "evt_retreat",
      ministryId: "ministry_default",
      title: "Winter Retreat",
      description: "Weekend retreat",
      type: "conference",
      status: "planning",
      startTime: "2099-01-10T18:00:00.000Z",
      endTime: "2099-01-12T12:00:00.000Z",
      location: "",
      targetGroup: "",
      contactOwnerId: "",
      budgetTarget: 300,
      autoGeneratedTimeline: [],
      createdAt: "2026-01-01T00:00:00.000Z"
    },
    {
      id: "evt_service",
      ministryId: "ministry_default",
      title: "Sunday Service",
      description: "Weekly gathering",
      type: "sunday_morning_service",
      status: "ready",
      startTime: "2099-02-10T10:00:00.000Z",
      endTime: "2099-02-10T11:00:00.000Z",
      location: "Auditorium",
      targetGroup: "Students",
      contactOwnerId: "usr_admin",
      budgetTarget: 0,
      autoGeneratedTimeline: [],
      createdAt: "2026-01-01T00:00:00.000Z"
    }
  ];
  const tasks: ActiveTask[] = [
    {
      id: "task_blocked",
      eventId: "evt_retreat",
      assignedUserId: "usr_admin",
      taskTitle: "Book cabin block",
      status: "blocked",
      dueDate: "2026-01-05T12:00:00.000Z",
      autoGenerated: true,
      timelineOffsetDays: -30
    }
  ];
  const expenses: EventExpense[] = [
    {
      id: "expense_food",
      eventId: "evt_retreat",
      categoryId: "food",
      description: "Deposit",
      amount: 450,
      timestamp: "2026-01-01T00:00:00.000Z"
    }
  ];
  const activity: ActivityLog[] = [];
  return { events, tasks, users, expenses, activity };
}
