import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/ministry/scope", () => ({
  resolveMinistryScope: vi.fn(async (s: { testMinistryId?: string }) => s.testMinistryId ?? "ministry-emerge")
}));

import type { AuthSession } from "@/lib/auth/server";
import {
  getMinistryEmmaReadiness,
  runMinistryPageServerChat
} from "@/lib/emma/ministry-page-server-chat";
import { __resetEmmaMockStoreForTests, getEmmaAuditTrail } from "@/lib/emma/repository";
import type { MinistryEmmaOverview } from "@/lib/emma/ministry-page-assistant";

type TestSession = AuthSession & { testMinistryId: string };

function session(role = "admin", id = "usr_admin"): TestSession {
  return {
    user: { id, email: `${id}@example.test`, fullName: "Test User", role },
    isMock: true,
    testMinistryId: "ministry-emerge"
  };
}

function overview(): MinistryEmmaOverview {
  return {
    events: [
      {
        id: "evt_1",
        title: "Fall Kickoff",
        description: "Invite students and parents into the new ministry year.",
        type: "weekly",
        startTime: "2026-08-01T18:00:00.000Z",
        endTime: "2026-08-01T20:00:00.000Z",
        location: "Student Center",
        targetGroup: "High School",
        status: "planning",
        priority: "normal",
        budgetTarget: 500,
        budgetActual: 125,
        volunteersNeeded: 6,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        createdAt: "2026-07-14T12:00:00.000Z"
      }
    ],
    tasks: [
      {
        id: "task_1",
        eventId: "evt_1",
        taskTitle: "Confirm worship leader",
        assignedUserId: "usr_admin",
        dueDate: "2026-07-25",
        status: "blocked",
        autoGenerated: true,
        timelineOffsetDays: -7,
        notes: ""
      }
    ],
    users: [
      {
        id: "usr_admin",
        email: "admin@example.test",
        firstName: "Alex",
        lastName: "Walker",
        role: "admin"
      }
    ],
    expenses: [
      {
        id: "expense_1",
        eventId: "evt_1",
        amount: 125,
        categoryId: "food",
        description: "Pizza deposit",
        timestamp: "2026-07-14T12:00:00.000Z"
      }
    ],
    activity: [
      {
        id: "act_1",
        eventId: "evt_1",
        taskId: "task_1",
        actorId: "usr_admin",
        type: "task_status_changed",
        message: "Moved task to blocked: Confirm worship leader",
        metadata: {},
        timestamp: "2026-07-14T12:00:00.000Z"
      }
    ]
  };
}

beforeEach(() => {
  __resetEmmaMockStoreForTests();
  delete process.env.EMMA_PROVIDER_MODE;
  delete process.env.EMMA_DEFAULT_PROVIDER;
  delete process.env.EMMA_DEFAULT_MODEL;
  delete process.env.GEMINI_API_KEY;
});

describe("ministry page server-backed EMMA chat", () => {
  it("returns an audited deterministic fallback when no live provider is configured", async () => {
    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "tasks", prompt: "Which tasks need follow-up?", selectedEventId: "evt_1" },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("audited_fallback");
    expect(result.data.provider).toBe("deterministic");
    expect(result.data.response.summary).toContain("open tasks");
    expect(result.data.proposalCreated).toBe(false);

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.request.workflow).toBe("GENERATE_MINISTRY_SUMMARY");
    expect(trail.runs[0]).toMatchObject({
      skillKey: "ministry_page_chat_fallback",
      status: "succeeded"
    });
    expect(trail.providerAttempts).toHaveLength(0);
  });

  it("creates an inert recommendation proposal from server chat when requested", async () => {
    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What should I open first?", selectedEventId: "evt_1", createProposal: true },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.proposalCreated).toBe(true);
    expect(result.data.proposalId).toEqual(expect.any(String));

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.proposals).toHaveLength(1);
    expect(trail.proposals[0]).toMatchObject({
      actionType: "none",
      riskLevel: "low",
      requiresApproval: false,
      targetRecordId: "evt_1"
    });
    expect(trail.proposals[0].payload).toMatchObject({
      proposalType: "ministry_page_recommendation",
      executed: false,
      page: "events"
    });
  });

  it("blocks roles outside Admin and Leader", async () => {
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What needs attention?" },
      session: session("student", "usr_student")
    });

    expect(result).toEqual({
      ok: false,
      error: {
        code: "FORBIDDEN",
        message: "Only Admin or Leader roles may use ministry EMMA chat."
      }
    });
  });

  it("reports live readiness without exposing secrets", () => {
    const readiness = getMinistryEmmaReadiness({
      session: session(),
      env: {
        ...process.env,
        EMMA_PROVIDER_MODE: "gemini",
        GEMINI_API_KEY: "secret-key",
        EMMA_DEFAULT_MODEL: "gemini-3.5-flash"
      }
    });

    expect(readiness).toMatchObject({
      liveProviderConfigured: true,
      provider: "gemini",
      model: "gemini-3.5-flash",
      status: "live"
    });
    expect(JSON.stringify(readiness)).not.toContain("secret-key");
  });
});
