import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/ministry/scope", () => ({
  resolveMinistryScope: vi.fn(async (s: { testMinistryId?: string }) => s.testMinistryId ?? "ministry-emerge")
}));

import type { AuthSession } from "@/lib/auth/server";
import {
  getMinistryEmmaReadiness,
  runMinistryPageServerChat
} from "@/lib/emma/ministry-page-server-chat";
import { __resetEmmaMockStoreForTests, __setEmmaRepositorySupabaseClientForTests, getEmmaAuditTrail } from "@/lib/emma/repository";
import type { MinistryEmmaOverview } from "@/lib/emma/ministry-page-assistant";

type TestSession = AuthSession & { testMinistryId: string };

function session(role = "admin", id = "usr_admin"): TestSession {
  return {
    user: { id, email: `${id}@example.test`, fullName: "Test User", role },
    isMock: true,
    testMinistryId: "ministry-emerge"
  };
}

function overview(): MinistryEmmaOverview {
  return {
    events: [
      {
        id: "evt_1",
        title: "Fall Kickoff",
        description: "Invite students and parents into the new ministry year.",
        type: "weekly",
        startTime: "2026-08-01T18:00:00.000Z",
        endTime: "2026-08-01T20:00:00.000Z",
        location: "Student Center",
        targetGroup: "High School",
        status: "planning",
        priority: "normal",
        budgetTarget: 500,
        budgetActual: 125,
        volunteersNeeded: 6,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        createdAt: "2026-07-14T12:00:00.000Z"
      }
    ],
    tasks: [
      {
        id: "task_1",
        eventId: "evt_1",
        taskTitle: "Confirm worship leader",
        assignedUserId: "usr_admin",
        dueDate: "2026-07-25",
        status: "blocked",
        autoGenerated: true,
        timelineOffsetDays: -7,
        notes: ""
      }
    ],
    users: [
      {
        id: "usr_admin",
        email: "admin@example.test",
        firstName: "Alex",
        lastName: "Walker",
        role: "admin"
      }
    ],
    expenses: [
      {
        id: "expense_1",
        eventId: "evt_1",
        amount: 125,
        categoryId: "food",
        description: "Pizza deposit",
        timestamp: "2026-07-14T12:00:00.000Z"
      }
    ],
    activity: [
      {
        id: "act_1",
        eventId: "evt_1",
        taskId: "task_1",
        actorId: "usr_admin",
        type: "task_status_changed",
        message: "Moved task to blocked: Confirm worship leader",
        metadata: {},
        timestamp: "2026-07-14T12:00:00.000Z"
      }
    ]
  };
}

beforeEach(() => {
  __resetEmmaMockStoreForTests();
  delete process.env.EMMA_PROVIDER_MODE;
  delete process.env.EMMA_DEFAULT_PROVIDER;
  delete process.env.EMMA_DEFAULT_MODEL;
  delete process.env.GEMINI_API_KEY;
  delete process.env.NEXT_PUBLIC_SUPABASE_URL;
  delete process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("ministry page server-backed EMMA chat", () => {
  it("returns an audited deterministic fallback when no live provider is configured", async () => {
    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "tasks", prompt: "Which tasks need follow-up?", selectedEventId: "evt_1" },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("audited_fallback");
    expect(result.data.provider).toBe("deterministic");
    expect(result.data.response.summary).toContain("open tasks");
    expect(result.data.proposalCreated).toBe(false);

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.request.workflow).toBe("GENERATE_MINISTRY_SUMMARY");
    expect(trail.runs[0]).toMatchObject({
      skillKey: "ministry_page_chat_fallback",
      status: "succeeded"
    });
    expect(trail.providerAttempts).toHaveLength(0);
  });

  it("creates an inert recommendation proposal from server chat when requested", async () => {
    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What should I open first?", selectedEventId: "evt_1", createProposal: true },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.proposalCreated).toBe(true);
    expect(result.data.proposalId).toEqual(expect.any(String));

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.proposals).toHaveLength(1);
    expect(trail.proposals[0]).toMatchObject({
      actionType: "none",
      riskLevel: "low",
      requiresApproval: false,
      targetRecordId: "evt_1"
    });
    expect(trail.proposals[0].payload).toMatchObject({
      proposalType: "ministry_page_recommendation",
      executed: false,
      page: "events"
    });
  });

  it("uses a configured live provider for preview dev-auth sessions", async () => {
    process.env.EMMA_PROVIDER_MODE = "openai";
    process.env.OPENAI_API_KEY = "test-openai-key";
    process.env.EMMA_DEFAULT_MODEL = "gpt-4o-mini";
    const fetchMock = vi.fn(async () =>
      new Response(
        JSON.stringify({
          model: "gpt-4o-mini",
          choices: [
            {
              message: {
                content: JSON.stringify({
                  summary: "Live model guidance for the events page.",
                  points: ["Review the event plan before changing assignments."],
                  nextActions: ["Open the highest-priority event first."],
                  confidence: 0.82,
                  warnings: []
                })
              }
            }
          ],
          usage: { total_tokens: 42 }
        }),
        { status: 200, headers: { "Content-Type": "application/json" } }
      )
    );
    vi.stubGlobal("fetch", fetchMock);

    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What should I open first?", selectedEventId: "evt_1" },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("live_provider");
    expect(result.data.provider).toBe("openai");
    expect(result.data.response.summary).toBe("Live model guidance for the events page.");
    expect(fetchMock).toHaveBeenCalledTimes(1);

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.runs[0]).toMatchObject({
      skillKey: "ministry_page_chat",
      status: "succeeded"
    });
    expect(trail.providerAttempts[0]).toMatchObject({
      provider: "openai",
      status: "success"
    });
  });

  it("falls back from invalid Gemini output to OpenAI when both providers are configured", async () => {
    process.env.EMMA_PROVIDER_MODE = "gemini";
    process.env.GEMINI_API_KEY = "test-gemini-key";
    process.env.OPENAI_API_KEY = "test-openai-key";
    process.env.EMMA_DEFAULT_MODEL = "gemini-3.5-flash";
    process.env.OPENAI_MODEL = "gpt-4o-mini";
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("generativelanguage.googleapis.com")) {
        return new Response(
          JSON.stringify({
            candidates: [{ content: { parts: [{ text: JSON.stringify({ invalid: true }) }] } }],
            usageMetadata: { totalTokenCount: 12 }
          }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({
          model: "gpt-4o-mini",
          choices: [
            {
              message: {
                content: JSON.stringify({
                  summary: "OpenAI failover guidance for the events page.",
                  points: ["Use the event readiness snapshot before making a decision."],
                  nextActions: ["Open the event with the most blocked work."],
                  confidence: 0.86,
                  warnings: []
                })
              }
            }
          ],
          usage: { total_tokens: 39 }
        }),
        { status: 200, headers: { "Content-Type": "application/json" } }
      );
    });
    vi.stubGlobal("fetch", fetchMock);

    const admin = session();
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What should I open first?", selectedEventId: "evt_1" },
      session: admin
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.providerMode).toBe("live_provider");
    expect(result.data.provider).toBe("openai");
    expect(result.data.model).toBe("gpt-4o-mini");
    expect(result.data.response.summary).toBe("OpenAI failover guidance for the events page.");
    expect(result.data.warnings).toContain("Primary EMMA provider failed safely; OpenAI failover returned a valid response.");
    expect(fetchMock).toHaveBeenCalledTimes(2);

    const trail = await getEmmaAuditTrail(admin, result.data.requestId);
    expect(trail.runs.map((run) => run.skillKey)).toEqual(["ministry_page_chat_openai_failover", "ministry_page_chat"]);
    expect(trail.providerAttempts.map((attempt) => `${attempt.provider}:${attempt.status}`)).toEqual([
      "openai:success",
      "gemini:failure"
    ]);
  });

  it("blocks roles outside Admin and Leader", async () => {
    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What needs attention?" },
      session: session("student", "usr_student")
    });

    expect(result).toEqual({
      ok: false,
      error: {
        code: "FORBIDDEN",
        message: "Only Admin or Leader roles may use ministry EMMA chat."
      }
    });
  });

  it("returns deterministic chat when audit persistence is unavailable", async () => {
    process.env.NEXT_PUBLIC_SUPABASE_URL = "https://example.supabase.co";
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = "anon-key";
    __setEmmaRepositorySupabaseClientForTests({
      from: () => ({
        insert: () => ({
          select: () => ({
            single: async () => ({ data: null, error: { message: "relation ai_requests does not exist" } })
          })
        })
      })
    });

    const result = await runMinistryPageServerChat({
      overview: overview(),
      rawInput: { page: "events", prompt: "What should I open first?", createProposal: true },
      session: { ...session(), isMock: false, accessToken: "token" }
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.requestId).toBe("local-fallback-request");
    expect(result.data.runId).toBe("local-fallback-run");
    expect(result.data.providerMode).toBe("audited_fallback");
    expect(result.data.proposalCreated).toBe(false);
    expect(result.data.warnings[0]).toMatch(/audit persistence was unavailable/i);
  });

  it("reports live readiness without exposing secrets", () => {
    const readiness = getMinistryEmmaReadiness({
      session: session(),
      env: {
        ...process.env,
        EMMA_PROVIDER_MODE: "gemini",
        GEMINI_API_KEY: "secret-key",
        EMMA_DEFAULT_MODEL: "gemini-3.5-flash"
      }
    });

    expect(readiness).toMatchObject({
      liveProviderConfigured: true,
      provider: "gemini",
      model: "gemini-3.5-flash",
      status: "live"
    });
    expect(JSON.stringify(readiness)).not.toContain("secret-key");
  });
});
