import { integrationAdapters } from "@/lib/adapters/integrations";
import { getMissingInformation } from "@/lib/missing-info";
import { deriveEventStatusFromTasks } from "@/lib/ministry/event-status";
import { defaultTemplateTasks } from "@/lib/templates";
import type {
  ActiveTask,
  ActivityLog,
  CommunicationPackage,
  EventExpense,
  EventType,
  EventWorkspace,
  IntegrationSyncLog,
  MinistryEvent,
  TaskStatus,
  User
} from "@/lib/types";
import { addDays, uid } from "@/lib/utils";

type GuestSandboxState = {
  users: User[];
  events: MinistryEvent[];
  tasks: ActiveTask[];
  communications: CommunicationPackage[];
  integrationLogs: IntegrationSyncLog[];
  expenses: EventExpense[];
  activity: ActivityLog[];
};

const globalGuestState = globalThis as typeof globalThis & {
  __leadEmergenceGuestSandboxes?: Map<string, GuestSandboxState>;
};

const sandboxes = globalGuestState.__leadEmergenceGuestSandboxes ?? new Map<string, GuestSandboxState>();
globalGuestState.__leadEmergenceGuestSandboxes = sandboxes;

export function getGuestSandbox(sessionId: string) {
  const existing = sandboxes.get(sessionId);
  if (existing) return existing;
  const next = createInitialSandbox();
  sandboxes.set(sessionId, next);
  return next;
}

export function getGuestOverview(sessionId: string) {
  const state = getGuestSandbox(sessionId);
  return {
    events: state.events,
    tasks: state.tasks,
    users: state.users,
    expenses: state.expenses,
    activity: state.activity
  };
}

export function getGuestWorkspace(sessionId: string, eventId: string): EventWorkspace | undefined {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return undefined;
  const expenses = state.expenses.filter((expense) => expense.eventId === eventId);
  return {
    event,
    tasks: state.tasks.filter((task) => task.eventId === eventId),
    communications: state.communications.filter((item) => item.eventId === eventId),
    integrationLogs: state.integrationLogs.filter((log) => log.eventId === eventId),
    expenses,
    missingInformation: getMissingInformation(event, expenses),
    activity: state.activity.filter((item) => item.eventId === eventId)
  };
}

export function createGuestEvent(sessionId: string, input: {
  title: string;
  description: string;
  type: EventType;
  startTime: string;
  endTime: string;
  location?: string;
  targetGroup?: string;
  budgetTarget?: number;
  budgetActual?: number;
  volunteersNeeded?: number;
  priority?: string;
  contactOwnerId?: string;
}) {
  const state = getGuestSandbox(sessionId);
  const event: MinistryEvent = {
    id: uid("guest_evt"),
    title: input.title,
    description: input.description,
    type: input.type,
    startTime: input.startTime,
    endTime: input.endTime,
    status: "planning",
    location: input.location,
    targetGroup: input.targetGroup,
    budgetTarget: input.budgetTarget,
    budgetActual: input.budgetActual ?? 0,
    volunteersNeeded: input.volunteersNeeded,
    priority: input.priority ?? "normal",
    contactOwnerId: input.contactOwnerId ?? state.users[0]?.id,
    autoGeneratedTimeline: [],
    notes: "Guest sandbox item. Nothing is saved outside this session.",
    createdAt: new Date().toISOString()
  };
  state.events.unshift(event);
  recordGuestActivity(state, { type: "event_created", eventId: event.id, message: `Guest created fake event: ${event.title}`, metadata: { persisted: false } });
  generateGuestTasks(state, event);
  return getGuestWorkspace(sessionId, event.id);
}

export function updateGuestEvent(sessionId: string, eventId: string, input: Partial<MinistryEvent>) {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return undefined;
  Object.assign(event, input);
  syncGuestEventStatus(state, eventId);
  recordGuestActivity(state, { type: "event_updated", eventId, message: `Guest updated fake event: ${event.title}`, metadata: { persisted: false } });
  return getGuestWorkspace(sessionId, eventId);
}

export function deleteGuestEvent(sessionId: string, eventId: string) {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return false;
  state.events = state.events.filter((item) => item.id !== eventId);
  state.tasks = state.tasks.filter((task) => task.eventId !== eventId);
  state.communications = state.communications.filter((item) => item.eventId !== eventId);
  state.integrationLogs = state.integrationLogs.filter((item) => item.eventId !== eventId);
  state.expenses = state.expenses.filter((item) => item.eventId !== eventId);
  recordGuestActivity(state, { type: "event_updated", message: `Guest deleted fake event: ${event.title}`, metadata: { persisted: false } });
  return true;
}

export function createGuestTask(sessionId: string, input: {
  eventId: string;
  taskTitle: string;
  dueDate: string;
  assignedUserId: string;
  status?: TaskStatus;
}) {
  const state = getGuestSandbox(sessionId);
  const task: ActiveTask = {
    id: uid("guest_task"),
    eventId: input.eventId,
    taskTitle: input.taskTitle,
    dueDate: input.dueDate,
    assignedUserId: input.assignedUserId,
    status: input.status ?? "todo",
    autoGenerated: false,
    timelineOffsetDays: 0,
    notes: "Guest sandbox task."
  };
  state.tasks.push(task);
  syncGuestEventStatus(state, input.eventId);
  recordGuestActivity(state, { type: "task_generated", eventId: input.eventId, taskId: task.id, message: `Guest added fake task: ${task.taskTitle}`, metadata: { persisted: false } });
  return task;
}

export function updateGuestTask(sessionId: string, taskId: string, input: Partial<ActiveTask>) {
  const state = getGuestSandbox(sessionId);
  const task = state.tasks.find((item) => item.id === taskId);
  if (!task) return undefined;
  Object.assign(task, input);
  syncGuestEventStatus(state, task.eventId);
  recordGuestActivity(state, { type: "task_edited", eventId: task.eventId, taskId, message: `Guest updated fake task: ${task.taskTitle}`, metadata: { persisted: false } });
  return task;
}

export function deleteGuestTask(sessionId: string, taskId: string) {
  const state = getGuestSandbox(sessionId);
  const task = state.tasks.find((item) => item.id === taskId);
  if (!task) return false;
  state.tasks = state.tasks.filter((item) => item.id !== taskId);
  syncGuestEventStatus(state, task.eventId);
  recordGuestActivity(state, { type: "task_edited", eventId: task.eventId, taskId, message: `Guest deleted fake task: ${task.taskTitle}`, metadata: { persisted: false } });
  return true;
}

export function generateGuestCommunicationPreview(sessionId: string, eventId: string) {
  const workspace = getGuestWorkspace(sessionId, eventId);
  if (!workspace) return undefined;
  const state = getGuestSandbox(sessionId);
  const createdAt = new Date().toISOString();
  const previews: CommunicationPackage[] = [
    {
      id: uid("guest_comm"),
      eventId,
      type: "parent_email",
      payload: {
        subject: `Guest preview: ${workspace.event.title}`,
        body: `Preview only - not sent.\n\nFamilies would receive a clear summary for ${workspace.event.title}. This guest sandbox never sends messages.`
      },
      status: "preview",
      createdAt
    },
    {
      id: uid("guest_comm"),
      eventId,
      type: "leader_brief",
      payload: {
        subject: `Guest leader brief: ${workspace.event.title}`,
        body: "Preview only - not sent. Leaders would see owners, timing, and follow-up questions here."
      },
      status: "preview",
      createdAt
    }
  ];
  state.communications.unshift(...previews);
  recordGuestActivity(state, { type: "communication_preview_generated", eventId, message: "Guest generated communication previews.", metadata: { persisted: false, sent: false } });
  return previews;
}

export function runGuestIntegrationStub(sessionId: string, eventId: string, type: "google_drive" | "propresenter" | "google_calendar" | "planning_center") {
  const workspace = getGuestWorkspace(sessionId, eventId);
  if (!workspace) return undefined;
  const state = getGuestSandbox(sessionId);
  const log = integrationAdapters[type].runStubAction(workspace.event);
  state.integrationLogs.unshift(log);
  recordGuestActivity(state, { type: "integration_stub_action", eventId, message: `Guest ran fake ${type.replace(/_/g, " ")} action.`, metadata: { persisted: false } });
  if (type === "google_drive") workspace.event.googleDriveFolderId = `guest-drive-${eventId}`;
  if (type === "propresenter") workspace.event.proPresenterPlaylistId = `guest-pro-${eventId}`;
  return log;
}

export function addGuestExpense(sessionId: string, input: { eventId: string; categoryId: string; amount: number; description: string }) {
  const state = getGuestSandbox(sessionId);
  const expense: EventExpense = { id: uid("guest_exp"), timestamp: new Date().toISOString(), ...input };
  state.expenses.unshift(expense);
  return expense;
}

function createInitialSandbox(): GuestSandboxState {
  const now = new Date();
  const launchNight = addDays(now.toISOString(), 4);
  const serveDay = addDays(now.toISOString(), 12);
  const retreat = addDays(now.toISOString(), 28);
  const users: User[] = [
    { id: "guest_admin", firstName: "Avery", lastName: "Director", email: "avery.director@example.test", role: "admin" },
    { id: "guest_leader", firstName: "Jordan", lastName: "Leader", email: "jordan.leader@example.test", role: "leader" },
    { id: "guest_volunteer", firstName: "Taylor", lastName: "Volunteer", email: "taylor.volunteer@example.test", role: "leader" }
  ];
  const events: MinistryEvent[] = [
    fakeEvent("guest_evt_launch", "Competition Launch Night", "A high-energy student event with check-in, games, worship, and follow-up workflows.", "high_school_event", launchNight, users[0].id, 900),
    fakeEvent("guest_evt_serve", "City Serve Saturday", "A service day with attendance tracking, leader assignments, and parent communication previews.", "missions_trip", serveDay, users[1].id, 1200),
    fakeEvent("guest_evt_retreat", "Fall Retreat Demo", "A retreat planning workspace with fake people, budget targets, and workflow readiness.", "conference", retreat, users[0].id, 6500)
  ];
  const state: GuestSandboxState = { users, events, tasks: [], communications: [], integrationLogs: [], expenses: [], activity: [] };
  events.forEach((event) => {
    generateGuestTasks(state, event);
    recordGuestActivity(state, { type: "event_created", eventId: event.id, message: `Loaded fake event: ${event.title}`, metadata: { attendance: event.type === "high_school_event" ? 47 : 31, workflows: 4 } });
  });
  state.expenses.push({ id: "guest_exp_1", eventId: "guest_evt_retreat", categoryId: "lodging", amount: 1500, description: "Fake venue deposit", timestamp: now.toISOString() });
  return state;
}

function fakeEvent(id: string, title: string, description: string, type: EventType, startTime: string, contactOwnerId: string, budgetTarget: number): MinistryEvent {
  return {
    id,
    title,
    description,
    type,
    startTime,
    endTime: addDays(startTime, type === "conference" ? 2 : 0),
    status: "planning",
    location: type === "missions_trip" ? "Hope Center" : "Student Center",
    targetGroup: "Competition guest demo",
    budgetTarget,
    budgetActual: 0,
    volunteersNeeded: type === "conference" ? 8 : 4,
    priority: type === "conference" ? "high" : "normal",
    contactOwnerId,
    autoGeneratedTimeline: [],
    notes: "Guest sandbox: fake event, people, attendance, and workflows.",
    createdAt: new Date().toISOString()
  };
}

function generateGuestTasks(state: GuestSandboxState, event: MinistryEvent) {
  const tasks = defaultTemplateTasks[event.type].map((template) => {
    const task: ActiveTask = {
      id: `guest_task_${event.id}_${template.id}`,
      eventId: event.id,
      taskTitle: template.taskTitle,
      dueDate: addDays(event.startTime, template.timelineOffsetDays),
      assignedUserId: state.users.find((user) => user.role === template.roleAssigned)?.id ?? state.users[0].id,
      status: "todo",
      autoGenerated: true,
      timelineOffsetDays: template.timelineOffsetDays,
      notes: "Guest sandbox workflow task."
    };
    state.tasks.push(task);
    return task;
  });
  event.autoGeneratedTimeline = tasks.map((task) => task.id);
  syncGuestEventStatus(state, event.id);
}

function syncGuestEventStatus(state: GuestSandboxState, eventId: string) {
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return;
  const nextStatus = deriveEventStatusFromTasks(state.tasks.filter((task) => task.eventId === eventId));
  if (nextStatus) event.status = nextStatus;
}

function recordGuestActivity(state: GuestSandboxState, input: Omit<ActivityLog, "id" | "actorId" | "timestamp">) {
  state.activity.unshift({
    id: uid("guest_act"),
    actorId: "guest_admin",
    timestamp: new Date().toISOString(),
    ...input
  });
}
