import { integrationAdapters } from "@/lib/adapters/integrations";
import { getMissingInformation } from "@/lib/missing-info";
import { deriveEventStatusFromTasks } from "@/lib/ministry/event-status";
import { defaultTemplateTasks } from "@/lib/templates";
import {
  buildEventSupportNotes,
  buildPlanningCenterSpaceOwnerDraft,
  supportTaskTitlesForNeeds,
  type EventSupportNeed
} from "@/lib/event-planning-support";
import { createLeadEmergenceDemoSandboxState } from "@/lib/guest/lead-emergence-demo-context";
import type {
  ActiveTask,
  ActivityLog,
  CommunicationPackage,
  EventExpense,
  EventType,
  EventWorkspace,
  IntegrationSyncLog,
  MinistryEvent,
  TaskStatus,
  User
} from "@/lib/types";
import { addDays, uid } from "@/lib/utils";

type GuestSandboxState = {
  users: User[];
  events: MinistryEvent[];
  tasks: ActiveTask[];
  communications: CommunicationPackage[];
  integrationLogs: IntegrationSyncLog[];
  expenses: EventExpense[];
  activity: ActivityLog[];
};

const globalGuestState = globalThis as typeof globalThis & {
  __leadEmergenceGuestSandboxes?: Map<string, GuestSandboxState>;
};

const sandboxes = globalGuestState.__leadEmergenceGuestSandboxes ?? new Map<string, GuestSandboxState>();
globalGuestState.__leadEmergenceGuestSandboxes = sandboxes;

export function getGuestSandbox(sessionId: string) {
  const existing = sandboxes.get(sessionId);
  if (existing) return existing;
  const next = createInitialSandbox();
  sandboxes.set(sessionId, next);
  return next;
}

export function getGuestOverview(sessionId: string) {
  const state = getGuestSandbox(sessionId);
  return {
    events: state.events,
    tasks: state.tasks,
    users: state.users,
    expenses: state.expenses,
    activity: state.activity
  };
}

export function getGuestWorkspace(sessionId: string, eventId: string): EventWorkspace | undefined {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return undefined;
  const expenses = state.expenses.filter((expense) => expense.eventId === eventId);
  return {
    event,
    tasks: state.tasks.filter((task) => task.eventId === eventId),
    communications: state.communications.filter((item) => item.eventId === eventId),
    integrationLogs: state.integrationLogs.filter((log) => log.eventId === eventId),
    expenses,
    missingInformation: getMissingInformation(event, expenses),
    activity: state.activity.filter((item) => item.eventId === eventId)
  };
}

export function createGuestEvent(sessionId: string, input: {
  title: string;
  description: string;
  type: EventType;
  startTime: string;
  endTime: string;
  location?: string;
  targetGroup?: string;
  budgetTarget?: number;
  budgetActual?: number;
  volunteersNeeded?: number;
  priority?: string;
  contactOwnerId?: string;
  supportNeeds?: EventSupportNeed[];
  supportNotes?: string;
  plannerRole?: string;
}) {
  const state = getGuestSandbox(sessionId);
  const event: MinistryEvent = {
    id: uid("guest_evt"),
    title: input.title,
    description: input.description,
    type: input.type,
    startTime: input.startTime,
    endTime: input.endTime,
    status: "planning",
    location: input.location,
    targetGroup: input.targetGroup,
    budgetTarget: input.budgetTarget,
    budgetActual: input.budgetActual ?? 0,
    volunteersNeeded: input.volunteersNeeded,
    priority: input.priority ?? "normal",
    contactOwnerId: input.contactOwnerId ?? state.users[0]?.id,
    autoGeneratedTimeline: [],
    notes: buildEventSupportNotes(input.supportNeeds ?? [], input.supportNotes) || "Guest sandbox item. Nothing is saved outside this session.",
    createdAt: new Date().toISOString()
  };
  state.events.unshift(event);
  recordGuestActivity(state, { type: "event_created", eventId: event.id, message: `Guest created demo event: ${event.title}`, metadata: { persisted: false } });
  generateGuestTasks(state, event);
  generateGuestSupportTasks(state, event, input.supportNeeds ?? []);
  stageGuestPlanningCenterSpaceOwnerDraft(state, event, input.plannerRole);
  return getGuestWorkspace(sessionId, event.id);
}

export function updateGuestEvent(sessionId: string, eventId: string, input: Partial<MinistryEvent>) {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return undefined;
  Object.assign(event, input);
  syncGuestEventStatus(state, eventId);
  recordGuestActivity(state, { type: "event_updated", eventId, message: `Guest updated demo event: ${event.title}`, metadata: { persisted: false } });
  return getGuestWorkspace(sessionId, eventId);
}

export function deleteGuestEvent(sessionId: string, eventId: string) {
  const state = getGuestSandbox(sessionId);
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return false;
  state.events = state.events.filter((item) => item.id !== eventId);
  state.tasks = state.tasks.filter((task) => task.eventId !== eventId);
  state.communications = state.communications.filter((item) => item.eventId !== eventId);
  state.integrationLogs = state.integrationLogs.filter((item) => item.eventId !== eventId);
  state.expenses = state.expenses.filter((item) => item.eventId !== eventId);
  recordGuestActivity(state, { type: "event_updated", message: `Guest deleted demo event: ${event.title}`, metadata: { persisted: false } });
  return true;
}

export function createGuestTask(sessionId: string, input: {
  eventId: string;
  taskTitle: string;
  dueDate: string;
  assignedUserId: string;
  status?: TaskStatus;
}) {
  const state = getGuestSandbox(sessionId);
  const task: ActiveTask = {
    id: uid("guest_task"),
    eventId: input.eventId,
    taskTitle: input.taskTitle,
    dueDate: input.dueDate,
    assignedUserId: input.assignedUserId,
    status: input.status ?? "todo",
    autoGenerated: false,
    timelineOffsetDays: 0,
    notes: "Guest sandbox task."
  };
  state.tasks.push(task);
  syncGuestEventStatus(state, input.eventId);
  recordGuestActivity(state, { type: "task_generated", eventId: input.eventId, taskId: task.id, message: `Guest added demo task: ${task.taskTitle}`, metadata: { persisted: false } });
  return task;
}

export function updateGuestTask(sessionId: string, taskId: string, input: Partial<ActiveTask>) {
  const state = getGuestSandbox(sessionId);
  const task = state.tasks.find((item) => item.id === taskId);
  if (!task) return undefined;
  Object.assign(task, input);
  syncGuestEventStatus(state, task.eventId);
  recordGuestActivity(state, { type: "task_edited", eventId: task.eventId, taskId, message: `Guest updated demo task: ${task.taskTitle}`, metadata: { persisted: false } });
  return task;
}

export function deleteGuestTask(sessionId: string, taskId: string) {
  const state = getGuestSandbox(sessionId);
  const task = state.tasks.find((item) => item.id === taskId);
  if (!task) return false;
  state.tasks = state.tasks.filter((item) => item.id !== taskId);
  syncGuestEventStatus(state, task.eventId);
  recordGuestActivity(state, { type: "task_edited", eventId: task.eventId, taskId, message: `Guest deleted demo task: ${task.taskTitle}`, metadata: { persisted: false } });
  return true;
}

export function generateGuestCommunicationPreview(sessionId: string, eventId: string) {
  const workspace = getGuestWorkspace(sessionId, eventId);
  if (!workspace) return undefined;
  const state = getGuestSandbox(sessionId);
  const createdAt = new Date().toISOString();
  const previews: CommunicationPackage[] = [
    {
      id: uid("guest_comm"),
      eventId,
      type: "parent_email",
      payload: {
        subject: `Guest preview: ${workspace.event.title}`,
        body: `Preview only - not sent.\n\nFamilies would receive a clear summary for ${workspace.event.title}. This guest sandbox never sends messages.`
      },
      status: "preview",
      createdAt
    },
    {
      id: uid("guest_comm"),
      eventId,
      type: "leader_brief",
      payload: {
        subject: `Guest leader brief: ${workspace.event.title}`,
        body: "Preview only - not sent. Leaders would see owners, timing, and follow-up questions here."
      },
      status: "preview",
      createdAt
    }
  ];
  state.communications.unshift(...previews);
  recordGuestActivity(state, { type: "communication_preview_generated", eventId, message: "Guest generated communication previews.", metadata: { persisted: false, sent: false } });
  return previews;
}

export function runGuestIntegrationStub(sessionId: string, eventId: string, type: "google_drive" | "propresenter" | "google_calendar" | "planning_center") {
  const workspace = getGuestWorkspace(sessionId, eventId);
  if (!workspace) return undefined;
  const state = getGuestSandbox(sessionId);
  const log = integrationAdapters[type].runStubAction(workspace.event);
  state.integrationLogs.unshift(log);
  recordGuestActivity(state, { type: "integration_stub_action", eventId, message: `Guest ran demo ${type.replace(/_/g, " ")} action.`, metadata: { persisted: false } });
  if (type === "google_drive") workspace.event.googleDriveFolderId = `guest-drive-${eventId}`;
  if (type === "propresenter") workspace.event.proPresenterPlaylistId = `guest-pro-${eventId}`;
  return log;
}

export function addGuestExpense(sessionId: string, input: { eventId: string; categoryId: string; amount: number; description: string }) {
  const state = getGuestSandbox(sessionId);
  const expense: EventExpense = { id: uid("guest_exp"), timestamp: new Date().toISOString(), ...input };
  state.expenses.unshift(expense);
  return expense;
}

function createInitialSandbox(): GuestSandboxState {
  return createLeadEmergenceDemoSandboxState();
}

function createLegacyInitialSandbox(): GuestSandboxState {
  const now = new Date();
  const launchNight = addDays(now.toISOString(), 4);
  const serveDay = addDays(now.toISOString(), 12);
  const retreat = addDays(now.toISOString(), 28);
  const users: User[] = [
    { id: "guest_admin", firstName: "Avery", lastName: "Director", email: "avery.director@example.test", role: "admin" },
    { id: "guest_leader", firstName: "Jordan", lastName: "Leader", email: "jordan.leader@example.test", role: "leader" },
    { id: "guest_volunteer", firstName: "Taylor", lastName: "Volunteer", email: "taylor.volunteer@example.test", role: "leader" },
    { id: "guest_worship", firstName: "Morgan", lastName: "Worship", email: "morgan.worship@example.test", role: "leader" },
    { id: "guest_care", firstName: "Riley", lastName: "Care", email: "riley.care@example.test", role: "leader" },
    { id: "guest_ops", firstName: "Sam", lastName: "Operations", email: "sam.operations@example.test", role: "leader" }
  ];
  const historicalEvents = buildHistoricalMemoryEvents(now, users);
  const events: MinistryEvent[] = [
    ...historicalEvents,
    fakeEvent("guest_evt_launch", "Competition Launch Night", "A submission walkthrough event connecting EMMA provider readiness, YouVersion Scripture handoff, Meridian review, and parent communication previews.", "high_school_event", launchNight, users[0].id, 900),
    fakeEvent("guest_evt_serve", "City Serve Saturday", "A service day demo with task ownership, leader assignments, and preview-only family communication.", "missions_trip", serveDay, users[1].id, 1200),
    fakeEvent("guest_evt_retreat", "Fall Retreat Demo", "A retreat planning workspace with demo people, budget targets, workflow readiness, and human-approved communication boundaries.", "conference", retreat, users[0].id, 6500)
  ];
  const state: GuestSandboxState = { users, events, tasks: [], communications: [], integrationLogs: [], expenses: [], activity: [] };
  historicalEvents.forEach((event, index) => seedHistoricalMemoryRecord(state, event, index));
  events.filter((event) => !event.archivedAt).forEach((event) => {
    generateGuestTasks(state, event);
    recordGuestActivity(state, { type: "event_created", eventId: event.id, message: `Loaded demo event: ${event.title}`, metadata: { attendance: event.type === "high_school_event" ? 47 : 31, workflows: 4 } });
  });
  seedSubmissionProofTasks(state, events.find((event) => event.id === "guest_evt_launch"));
  state.expenses.push({ id: "guest_exp_1", eventId: "guest_evt_retreat", categoryId: "lodging", amount: 1500, description: "Modeled venue deposit", timestamp: now.toISOString() });
  return state;
}

function fakeEvent(id: string, title: string, description: string, type: EventType, startTime: string, contactOwnerId: string, budgetTarget: number): MinistryEvent {
  return {
    id,
    title,
    description,
    type,
    startTime,
    endTime: addDays(startTime, type === "conference" ? 2 : 0),
    status: "planning",
    location: type === "missions_trip" ? "Hope Center" : "Student Center",
    targetGroup: "Competition guest demo",
    budgetTarget,
    budgetActual: 0,
    volunteersNeeded: type === "conference" ? 8 : 4,
    priority: type === "conference" ? "high" : "normal",
    contactOwnerId,
    autoGeneratedTimeline: [],
    notes: "Guest sandbox: demo event, people, attendance, AI-readiness proof, and preview-only workflows.",
    createdAt: new Date().toISOString()
  };
}

function buildHistoricalMemoryEvents(now: Date, users: User[]): MinistryEvent[] {
  const currentYear = now.getFullYear();
  const year = (yearsAgo: number) => currentYear - yearsAgo;
  return [
    fakeHistoricalEvent({
      id: "guest_hist_retreat_2021",
      title: "Fall Retreat 2021",
      description: "Archived public demo retreat memory with attendance, budget, volunteer load, and follow-up notes.",
      type: "conference",
      year: year(5),
      month: 10,
      day: 1,
      days: 2,
      ownerId: users[0].id,
      location: "Cedars Camp",
      targetGroup: "High school students",
      budgetTarget: 5200,
      budgetActual: 4985,
      volunteersNeeded: 6,
      notes: "Public demo memory. Planning Center snapshot: 58 checked in, 9 first-time students. Debrief named follow-up calls as the main missed opportunity."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_retreat_2022",
      title: "Fall Retreat 2022",
      description: "Archived public demo retreat memory showing stronger parent communication and tighter cabin-leader ratios.",
      type: "conference",
      year: year(4),
      month: 9,
      day: 30,
      days: 2,
      ownerId: users[0].id,
      location: "Cedars Camp",
      targetGroup: "High school students",
      budgetTarget: 5600,
      budgetActual: 5790,
      volunteersNeeded: 8,
      notes: "Public demo memory. Planning Center snapshot: 66 checked in, 14 first-time students. Follow-up improved after leaders received a Drive debrief within 72 hours."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_retreat_2023",
      title: "Fall Retreat 2023",
      description: "Archived public demo retreat memory connecting worship planning, budget pressure, and leader debrief outcomes.",
      type: "conference",
      year: year(3),
      month: 10,
      day: 6,
      days: 2,
      ownerId: users[1].id,
      location: "Pine Ridge Camp",
      targetGroup: "High school students",
      budgetTarget: 6100,
      budgetActual: 6375,
      volunteersNeeded: 9,
      notes: "Public demo memory. Planning Center snapshot: 71 checked in. ProPresenter playlist was ready early; transportation and scholarship decisions created late pressure."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_retreat_2024",
      title: "Fall Retreat 2024",
      description: "Archived public demo retreat memory with earlier task ownership and a stronger post-event story collection process.",
      type: "conference",
      year: year(2),
      month: 10,
      day: 4,
      days: 2,
      ownerId: users[0].id,
      location: "Pine Ridge Camp",
      targetGroup: "High school students",
      budgetTarget: 6500,
      budgetActual: 6410,
      volunteersNeeded: 10,
      notes: "Public demo memory. Planning Center snapshot: 76 checked in. Drive debrief captured five student stories and a recommendation to recruit cabin leaders six weeks earlier."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_serve_2022",
      title: "City Serve Saturday 2022",
      description: "Archived public demo serve-day memory showing partner confirmation and transportation readiness.",
      type: "missions_trip",
      year: year(4),
      month: 4,
      day: 23,
      days: 0,
      ownerId: users[2].id,
      location: "Hope Center",
      targetGroup: "Middle and high school students",
      budgetTarget: 900,
      budgetActual: 835,
      volunteersNeeded: 7,
      notes: "Public demo memory. Planning Center snapshot: 42 participants. Partner confirmation arrived 10 days out, which compressed parent communication."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_serve_2023",
      title: "City Serve Saturday 2023",
      description: "Archived public demo serve-day memory with earlier partner details and better team assignments.",
      type: "missions_trip",
      year: year(3),
      month: 4,
      day: 22,
      days: 0,
      ownerId: users[2].id,
      location: "Hope Center",
      targetGroup: "Middle and high school students",
      budgetTarget: 950,
      budgetActual: 910,
      volunteersNeeded: 8,
      notes: "Public demo memory. Planning Center snapshot: 49 participants. Earlier partner confirmation reduced last-week task changes."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_serve_2024",
      title: "City Serve Saturday 2024",
      description: "Archived public demo serve-day memory showing repeated pressure around drivers and supply handoffs.",
      type: "missions_trip",
      year: year(2),
      month: 4,
      day: 27,
      days: 0,
      ownerId: users[5].id,
      location: "Hope Center",
      targetGroup: "Middle and high school students",
      budgetTarget: 1100,
      budgetActual: 1180,
      volunteersNeeded: 9,
      notes: "Public demo memory. Planning Center snapshot: 55 participants. Debrief recommended assigning drivers before announcing registration."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_worship_2023",
      title: "Winter Worship Night 2023",
      description: "Archived public demo worship memory connecting room setup, ProPresenter readiness, and student response follow-up.",
      type: "combined_event",
      year: year(3),
      month: 2,
      day: 12,
      days: 0,
      ownerId: users[3].id,
      location: "Worship Center",
      targetGroup: "Students and families",
      budgetTarget: 1400,
      budgetActual: 1325,
      volunteersNeeded: 6,
      notes: "Public demo memory. ProPresenter playlist was approved three days early. Leader debrief requested clearer prayer-team follow-up."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_worship_2024",
      title: "Winter Worship Night 2024",
      description: "Archived public demo worship memory with stronger volunteer ownership and better family preview communication.",
      type: "combined_event",
      year: year(2),
      month: 2,
      day: 18,
      days: 0,
      ownerId: users[3].id,
      location: "Worship Center",
      targetGroup: "Students and families",
      budgetTarget: 1500,
      budgetActual: 1475,
      volunteersNeeded: 7,
      notes: "Public demo memory. Planning Center snapshot: 88 attendees. Drive folder stored leader brief, service order, and parent preview."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_leadership_2021",
      title: "Student Leadership Night 2021",
      description: "Archived public demo leadership night memory focused on student ownership and next-step conversations.",
      type: "high_school_event",
      year: year(5),
      month: 8,
      day: 15,
      days: 0,
      ownerId: users[4].id,
      location: "Student Center",
      targetGroup: "Student leaders",
      budgetTarget: 450,
      budgetActual: 390,
      volunteersNeeded: 3,
      notes: "Public demo memory. Debrief tracked 11 student leaders and recommended pairing every event role with a mentor."
    }),
    fakeHistoricalEvent({
      id: "guest_hist_leadership_2024",
      title: "Student Leadership Night 2024",
      description: "Archived public demo leadership night memory showing student role continuity across the school year.",
      type: "high_school_event",
      year: year(2),
      month: 8,
      day: 11,
      days: 0,
      ownerId: users[4].id,
      location: "Student Center",
      targetGroup: "Student leaders",
      budgetTarget: 600,
      budgetActual: 575,
      volunteersNeeded: 4,
      notes: "Public demo memory. Planning Center snapshot: 19 student leaders. Follow-up notes flagged worship, welcome, and tech teams as healthy next-step lanes."
    })
  ];
}

function fakeHistoricalEvent(input: {
  id: string;
  title: string;
  description: string;
  type: EventType;
  year: number;
  month: number;
  day: number;
  days: number;
  ownerId: string;
  location: string;
  targetGroup: string;
  budgetTarget: number;
  budgetActual: number;
  volunteersNeeded: number;
  notes: string;
}): MinistryEvent {
  const startTime = new Date(input.year, input.month - 1, input.day, 18, 0, 0, 0).toISOString();
  const endTime = addDays(startTime, input.days);
  return {
    id: input.id,
    title: input.title,
    description: input.description,
    type: input.type,
    startTime,
    endTime,
    status: "completed",
    location: input.location,
    targetGroup: input.targetGroup,
    budgetTarget: input.budgetTarget,
    budgetActual: input.budgetActual,
    volunteersNeeded: input.volunteersNeeded,
    priority: input.type === "conference" ? "high" : "normal",
    contactOwnerId: input.ownerId,
    assignedLeaderIds: [input.ownerId],
    autoGeneratedTimeline: [],
    googleCalendarEventId: `guest-calendar-${input.id}`,
    googleCalendarEventUrl: `https://calendar.google.com/calendar/event?eid=${input.id}`,
    googleDriveFolderId: `guest-drive-${input.id}`,
    googleDriveFolderUrl: `https://drive.google.com/drive/folders/${input.id}`,
    googleImportStatus: "imported_from_google",
    proPresenterPlaylistId: input.type === "combined_event" || input.type === "conference" ? `guest-pro-${input.id}` : undefined,
    notes: input.notes,
    archivedAt: addDays(endTime, 14),
    archivedByUserId: input.ownerId,
    archiveReason: "Archived public demo history for organizational memory.",
    createdAt: addDays(startTime, -90)
  };
}

function seedHistoricalMemoryRecord(state: GuestSandboxState, event: MinistryEvent, index: number) {
  const taskTemplates = [
    {
      title: "Review Planning Center attendance snapshot",
      offset: -45,
      notes: "Public demo only: modeled attendance, first-time students, and leader ratio were reviewed before planning the next rhythm."
    },
    {
      title: "Confirm volunteer ownership against last year's load",
      offset: -30,
      notes: "Public demo only: previous volunteer gaps shaped the owner list for this archived event."
    },
    {
      title: "Save Drive debrief and story notes",
      offset: 2,
      notes: "Public demo only: post-event debrief, follow-up stories, and next recommendations were stored as organizational memory."
    },
    {
      title: "Draft parent and leader follow-up preview",
      offset: 3,
      notes: "Preview only: communication history models drafts that required human approval and were never sent by the sandbox."
    }
  ];

  const tasks = taskTemplates.map((template, taskIndex) => {
    const task: ActiveTask = {
      id: `guest_task_${event.id}_memory_${taskIndex}`,
      eventId: event.id,
      taskTitle: template.title,
      dueDate: addDays(event.startTime, template.offset),
      assignedUserId: state.users[(index + taskIndex) % state.users.length]?.id ?? state.users[0]?.id ?? "",
      status: "done",
      autoGenerated: true,
      timelineOffsetDays: template.offset,
      notes: template.notes
    };
    state.tasks.push(task);
    return task;
  });
  event.autoGeneratedTimeline = tasks.map((task) => task.id);

  state.expenses.push(
    {
      id: `guest_exp_${event.id}_actual`,
      eventId: event.id,
      categoryId: event.type === "conference" ? "lodging" : "supplies",
      amount: event.budgetActual ?? 0,
      description: `Public demo archived actual for ${event.title}`,
      timestamp: addDays(event.endTime, 4)
    },
    {
      id: `guest_exp_${event.id}_followup`,
      eventId: event.id,
      categoryId: "follow_up",
      amount: event.type === "conference" ? 225 : 75,
      description: "Public demo follow-up, care, and leader debrief costs",
      timestamp: addDays(event.endTime, 6)
    }
  );

  state.communications.push({
    id: `guest_comm_${event.id}_leader_followup`,
    eventId: event.id,
    type: "leader_brief",
    payload: {
      subject: `Archived preview: ${event.title} debrief`,
      body: "Preview only - not sent. This public demo record models how leader debriefs, next-step stories, and follow-up needs would remain searchable."
    },
    status: "preview",
    createdAt: addDays(event.endTime, 2)
  });

  (["planning_center", "google_calendar", "google_drive", "propresenter"] as const).forEach((integrationType) => {
    if (integrationType === "propresenter" && !event.proPresenterPlaylistId) return;
    state.integrationLogs.push({
      id: `guest_sync_${event.id}_${integrationType}`,
      integrationType,
      eventId: event.id,
      status: "stub_mode",
      details: {
        action: `${integrationType.replace(/_/g, " ")} memory import`,
        message: `Public demo stub record for ${event.title}. No live ${integrationType.replace(/_/g, " ")} account was contacted.`
      },
      timestamp: addDays(event.endTime, 1)
    });
  });

  recordGuestActivity(state, {
    type: "integration_stub_action",
    eventId: event.id,
    message: `Loaded archived public demo memory: ${event.title}`,
    metadata: {
      persisted: false,
      historical: true,
      attendanceModeled: true,
      externalSync: false
    }
  });
}

function seedSubmissionProofTasks(state: GuestSandboxState, event: MinistryEvent | undefined) {
  if (!event) return;
  const proofTasks: Array<{ title: string; offset: number; notes: string }> = [
    {
      title: "Verify EMMA provider readiness badge",
      offset: -7,
      notes: "Competition proof: EMMA names the provider that actually answers for signed-in production users; guest mode stays read-only demo guidance."
    },
    {
      title: "Open YouVersion reference handoff",
      offset: -6,
      notes: "Competition proof: Lead Emergence stores approved references and opens Bible.com surfaces instead of storing Bible text."
    },
    {
      title: "Review Meridian image-bearing journey",
      offset: -5,
      notes: "Competition proof: Gloo/Meridian drafts are shaped for leader approval before students receive group guidance."
    },
    {
      title: "Confirm no AI sends without human approval",
      offset: -4,
      notes: "Competition proof: communication outputs remain preview-only until a person approves the next action."
    }
  ];

  proofTasks.forEach((proofTask, index) => {
    const task: ActiveTask = {
      id: `guest_task_${event.id}_submission_${index}`,
      eventId: event.id,
      taskTitle: proofTask.title,
      dueDate: addDays(event.startTime, proofTask.offset),
      assignedUserId: state.users[index % state.users.length]?.id ?? state.users[0]?.id ?? "",
      status: index === 0 ? "done" : "todo",
      autoGenerated: true,
      timelineOffsetDays: proofTask.offset,
      notes: proofTask.notes
    };
    state.tasks.push(task);
    recordGuestActivity(state, {
      type: "task_generated",
      eventId: event.id,
      taskId: task.id,
      message: `Loaded submission proof task: ${proofTask.title}`,
      metadata: { persisted: false, competitionProof: true }
    });
  });
  syncGuestEventStatus(state, event.id);
}

function generateGuestTasks(state: GuestSandboxState, event: MinistryEvent) {
  const tasks = defaultTemplateTasks[event.type].map((template) => {
    const task: ActiveTask = {
      id: `guest_task_${event.id}_${template.id}`,
      eventId: event.id,
      taskTitle: template.taskTitle,
      dueDate: addDays(event.startTime, template.timelineOffsetDays),
      assignedUserId: state.users.find((user) => user.role === template.roleAssigned)?.id ?? state.users[0].id,
      status: "todo",
      autoGenerated: true,
      timelineOffsetDays: template.timelineOffsetDays,
      notes: "Guest sandbox workflow task."
    };
    state.tasks.push(task);
    return task;
  });
  event.autoGeneratedTimeline = tasks.map((task) => task.id);
  syncGuestEventStatus(state, event.id);
}

function generateGuestSupportTasks(state: GuestSandboxState, event: MinistryEvent, supportNeeds: EventSupportNeed[]) {
  const dueDate = addDays(event.startTime, -14);
  supportTaskTitlesForNeeds(supportNeeds).forEach((title) => {
    const task: ActiveTask = {
      id: uid("guest_task"),
      eventId: event.id,
      taskTitle: title,
      dueDate,
      assignedUserId: event.contactOwnerId ?? state.users[0]?.id ?? "",
      status: "todo",
      autoGenerated: true,
      timelineOffsetDays: -14,
      notes: "Guest sandbox support task."
    };
    state.tasks.push(task);
    recordGuestActivity(state, { type: "task_generated", eventId: event.id, taskId: task.id, message: `Guest generated support task: ${title}`, metadata: { persisted: false, support: true } });
  });
  syncGuestEventStatus(state, event.id);
}

function stageGuestPlanningCenterSpaceOwnerDraft(state: GuestSandboxState, event: MinistryEvent, plannerRole?: string) {
  const draft = buildPlanningCenterSpaceOwnerDraft(event, state.users, plannerRole);
  if (!draft) return;
  state.communications.unshift({ ...draft, id: uid("guest_comm") });
  recordGuestActivity(state, { type: "communication_preview_generated", eventId: event.id, message: `Guest drafted Planning Center space-owner email for ${event.title}`, metadata: { persisted: false, sent: false } });
}

function syncGuestEventStatus(state: GuestSandboxState, eventId: string) {
  const event = state.events.find((item) => item.id === eventId);
  if (!event) return;
  const nextStatus = deriveEventStatusFromTasks(state.tasks.filter((task) => task.eventId === eventId));
  if (nextStatus) event.status = nextStatus;
}

function recordGuestActivity(state: GuestSandboxState, input: Omit<ActivityLog, "id" | "actorId" | "timestamp">) {
  state.activity.unshift({
    id: uid("guest_act"),
    actorId: "guest_admin",
    timestamp: new Date().toISOString(),
    ...input
  });
}
