import { describe, expect, it } from "vitest";

import { buildGuestEmmaResponse } from "@/lib/guest/stock-ai";
import type { MinistryEmmaOverview } from "@/lib/emma/ministry-page-assistant";

describe("guest EMMA stock responses", () => {
  it("answers recurring Bible study prompts as a decision brief", () => {
    const response = buildGuestEmmaResponse({
      overview: guestOverview(),
      page: "dashboard",
      prompt: "what would it take to add a weds bible study for high school?"
    });

    expect(response.summary).toContain("Wednesday high-school Bible study");
    expect(response.summary).toContain("capacity-and-discernment brief");
    expect(response.points.join(" ")).toContain("Evidence still missing");
    expect(response.nextActions).toContain("Confirm one owner, 2 in-room adults, and a backup/follow-up leader before announcing.");
  });

  it("answers volunteer capacity prompts with a bounded demo estimate", () => {
    const response = buildGuestEmmaResponse({
      overview: guestOverview(),
      page: "dashboard",
      prompt: "how many extra volunteers might we need?"
    });

    expect(response.summary).toContain("3-4 extra committed adults");
    expect(response.points).toContain("Minimum baseline: 2 consistent adults in the room before launch.");
    expect(response.nextActions).toContain("Use a four-week pilot before treating this as a permanent rhythm.");
  });
});

function guestOverview(): MinistryEmmaOverview {
  return {
    events: [
      {
        id: "guest_evt_1",
        title: "Fall Retreat Demo",
        description: "Public demo retreat",
        type: "conference",
        startTime: "2099-09-01T18:00:00.000Z",
        endTime: "2099-09-03T12:00:00.000Z",
        status: "planning",
        location: "Demo Camp",
        targetGroup: "High School",
        volunteersNeeded: 6,
        autoGeneratedTimeline: [],
        createdAt: "2026-07-01T00:00:00.000Z"
      },
      {
        id: "guest_evt_2",
        title: "Wednesday Worship Demo",
        description: "Public demo worship night",
        type: "small_group_gathering",
        startTime: "2099-09-10T18:00:00.000Z",
        endTime: "2099-09-10T20:00:00.000Z",
        status: "planning",
        location: "Student Center",
        targetGroup: "Students",
        volunteersNeeded: 4,
        autoGeneratedTimeline: [],
        createdAt: "2026-07-01T00:00:00.000Z"
      }
    ],
    tasks: [
      {
        id: "guest_task_1",
        eventId: "guest_evt_1",
        taskTitle: "Confirm leader coverage",
        assignedUserId: "guest_leader",
        dueDate: "2099-08-20",
        status: "todo",
        autoGenerated: true,
        timelineOffsetDays: -14
      }
    ],
    users: [],
    expenses: [],
    activity: []
  };
}
