import { describe, expect, it } from "vitest";
import { buildDashboardAttention } from "@/lib/dashboard-attention";
import type { DiscussionWorkflowState } from "@/lib/scripture/discussion-workflow";
import type { ActiveTask, MinistryEvent, User } from "@/lib/types";

const event = {
  id: "event-1",
  title: "Fall Retreat",
  description: "",
  type: "conference",
  startTime: "2026-09-20T14:00:00.000Z",
  endTime: "2026-09-20T20:00:00.000Z",
  status: "planning",
  autoGeneratedTimeline: [],
  createdAt: "2026-07-01T00:00:00.000Z"
} as MinistryEvent;

const user = { id: "leader-1", firstName: "Alex", lastName: "Walker", role: "leader" } as User;

function task(id: string, status: ActiveTask["status"], dueDate: string): ActiveTask {
  return { id, eventId: event.id, taskTitle: id, dueDate, assignedUserId: user.id, status, autoGenerated: false, timelineOffsetDays: 0 };
}

describe("dashboard attention composition", () => {
  it("orders blocked and overdue work before near-term inventory", () => {
    const result = buildDashboardAttention(
      {
        events: [event],
        users: [user],
        tasks: [
          task("due soon", "todo", "2026-07-17T12:00:00.000Z"),
          task("overdue", "in_progress", "2026-07-10T12:00:00.000Z"),
          task("blocked", "blocked", "2026-07-30T12:00:00.000Z")
        ]
      },
      null,
      new Date("2026-07-14T12:00:00.000Z")
    );

    expect(result.decisions.map((item) => item.id)).toEqual(["blocked", "overdue", "due soon"]);
    expect(result.studentCare.available).toBe(false);
  });

  it("only surfaces tasks attached to active event rows", () => {
    const archivedEvent = { ...event, id: "event-archived", archivedAt: "2026-07-01T00:00:00.000Z" } as MinistryEvent;
    const activeTask = task("active", "blocked", "2026-07-30T12:00:00.000Z");
    const archivedTask = { ...task("archived", "blocked", "2026-07-30T12:00:00.000Z"), eventId: archivedEvent.id };
    const orphanedTask = { ...task("orphaned", "blocked", "2026-07-30T12:00:00.000Z"), eventId: "missing-event" };

    const result = buildDashboardAttention(
      {
        events: [event, archivedEvent],
        users: [user],
        tasks: [activeTask, archivedTask, orphanedTask]
      },
      null,
      new Date("2026-07-14T12:00:00.000Z")
    );

    expect(result.decisions.map((item) => item.id)).toEqual(["active"]);
  });

  it("returns only care-safe student identity and status copy", () => {
    const discussion = {
      readiness: { liveStorage: false, localStorage: true, canSubmit: true, gloo: false, slack: false, message: "Local review is ready." },
      prompts: [{
        id: "prompt-1",
        submittedByName: "Jordan Student",
        submittedByEmail: "jordan@example.com",
        question: "Private question content",
        scriptureReference: "Psalm 23",
        safetyLabel: "needs_leader_care",
        createdAt: "2026-07-14T12:00:00.000Z"
      }]
    } as DiscussionWorkflowState;

    const result = buildDashboardAttention({ events: [event], tasks: [], users: [user] }, discussion);

    expect(result.people[0].title).toBe("Jordan Student");
    expect(result.people[0].summary).not.toContain("Private question content");
    expect(result.studentCare.available).toBe(true);
  });
});
