import { describe, expect, it } from "vitest";

import { getEventsForTab, groupEventsByTimeframe } from "@/lib/event-timeframes";
import type { MinistryEvent } from "@/lib/types";

const july = new Date(2026, 6, 15, 12);

function event(id: string, startTime: string, endTime = startTime, archivedAt?: string): MinistryEvent {
  return {
    id,
    title: id,
    description: "Test event vision",
    type: "sunday_morning_service",
    startTime,
    endTime,
    status: "planning",
    autoGeneratedTimeline: [],
    createdAt: "2026-01-01T12:00:00.000Z",
    archivedAt
  };
}

describe("event timeframes", () => {
  it("includes the first day, middle, and last day of the local month", () => {
    const groups = groupEventsByTimeframe([
      event("first", "2026-07-01"),
      event("middle", "2026-07-15T18:00:00.000Z"),
      event("last", "2026-07-31")
    ], july);

    expect(getEventsForTab("thisMonth", groups).map((item) => item.id)).toEqual(["first", "middle", "last"]);
  });

  it("excludes prior, next, and archived events", () => {
    const groups = groupEventsByTimeframe([
      event("prior", "2026-06-30"),
      event("next", "2026-08-01"),
      event("archived", "2026-07-20", "2026-07-20", "2026-07-21T00:00:00.000Z")
    ], july);

    expect(getEventsForTab("thisMonth", groups)).toEqual([]);
  });

  it("includes multi-day events that overlap either edge of the month", () => {
    const groups = groupEventsByTimeframe([
      event("starts-before", "2026-06-29", "2026-07-02"),
      event("ends-after", "2026-07-30", "2026-08-02")
    ], july);

    expect(getEventsForTab("thisMonth", groups).map((item) => item.id)).toEqual(["starts-before", "ends-after"]);
  });

  it("treats date-only guest values as local dates and supports authenticated ISO values", () => {
    const groups = groupEventsByTimeframe([
      event("guest-seeded", "2026-07-01"),
      event("authenticated", "2026-07-31T23:30:00.000Z")
    ], july);

    expect(getEventsForTab("thisMonth", groups).map((item) => item.id)).toEqual(["guest-seeded", "authenticated"]);
  });
});
