import { describe, expect, it } from "vitest";
import {
  buildEventSupportNotes,
  buildPlanningCenterSpaceOwnerDraft,
  needsPlanningCenterSpaceOwnerDraft,
  normalizeSupportNeeds,
  supportTaskTitlesForNeeds
} from "@/lib/event-planning-support";
import type { MinistryEvent, User } from "@/lib/types";

const users: User[] = [
  { id: "director", firstName: "Avery", lastName: "Director", email: "avery@example.test", role: "admin" },
  { id: "leader", firstName: "Jordan", lastName: "Leader", email: "jordan@example.test", role: "leader" }
];

function event(location: string, contactOwnerId = "leader"): MinistryEvent {
  return {
    id: "evt_test",
    title: "Parent Dinner",
    description: "Dinner for families and leaders.",
    type: "combined_event",
    startTime: "2026-08-10T23:00:00.000Z",
    endTime: "2026-08-11T01:00:00.000Z",
    status: "planning",
    location,
    contactOwnerId,
    autoGeneratedTimeline: [],
    createdAt: "2026-07-25T12:00:00.000Z"
  };
}

describe("event planning support helpers", () => {
  it("normalizes EMMA support needs and ignores unsupported values", () => {
    expect(normalizeSupportNeeds(["production", "hospitality", "production", "security"])).toEqual([
      "production",
      "hospitality"
    ]);
    expect(supportTaskTitlesForNeeds(["production", "room_setup", "hospitality"])).toEqual([
      "Confirm production support needs",
      "Coordinate room configuration with Fix-It Team",
      "Confirm hospitality and food plan"
    ]);
  });

  it("drafts Planning Center space-owner email for leader-owned events outside the youth room", () => {
    const target = event("Fellowship Hall");

    expect(needsPlanningCenterSpaceOwnerDraft(target, users, "leader")).toBe(true);
    expect(buildPlanningCenterSpaceOwnerDraft(target, users, "leader")).toMatchObject({
      type: "space_owner_email",
      payload: {
        subject: "Space availability request: Parent Dinner"
      },
      status: "preview"
    });
  });

  it("keys room-owner email drafting to the planner role", () => {
    expect(needsPlanningCenterSpaceOwnerDraft(event("Fellowship Hall", "director"), users, "leader")).toBe(true);
    expect(needsPlanningCenterSpaceOwnerDraft(event("Fellowship Hall", "leader"), users, "admin")).toBe(false);
  });

  it("does not draft room-owner email for directors or youth-room locations", () => {
    expect(needsPlanningCenterSpaceOwnerDraft(event("Fellowship Hall", "director"), users)).toBe(false);
    expect(needsPlanningCenterSpaceOwnerDraft(event("Youth Room"), users, "leader")).toBe(false);
    expect(needsPlanningCenterSpaceOwnerDraft(event("Student Center"), users, "leader")).toBe(false);
  });

  it("builds support notes from selected EMMA support prompts", () => {
    expect(buildEventSupportNotes(["production", "hospitality"], "Need handheld mics and dinner for 80.")).toContain(
      "Support requested: Production, Hospitality / food"
    );
  });
});
