import { integrationAdapters } from "./adapters/integrations";
import { getMissingInformation } from "./missing-info";
import { defaultTemplateTasks } from "./templates";
import type {
  ActiveTask,
  ActivityLog,
  CommunicationPackage,
  EventExpense,
  EventType,
  EventWorkspace,
  IntegrationSyncLog,
  MinistryEvent,
  TaskStatus,
  User
} from "./types";
import { addDays, uid } from "./utils";

type MockStoreState = {
  version: number;
  initialized: boolean;
  users: User[];
  events: MinistryEvent[];
  tasks: ActiveTask[];
  communications: CommunicationPackage[];
  integrationLogs: IntegrationSyncLog[];
  expenses: EventExpense[];
  activity: ActivityLog[];
};

function createInitialStore(): MockStoreState {
  const now = new Date();
  const thisWeekStart = new Date(now);
  thisWeekStart.setDate(thisWeekStart.getDate() + 2);
  thisWeekStart.setHours(18, 0, 0, 0);

  const fridayStart = new Date(now);
  fridayStart.setDate(fridayStart.getDate() + 3);
  fridayStart.setHours(19, 0, 0, 0);

  const thisMonthStart = new Date(now);
  thisMonthStart.setDate(thisMonthStart.getDate() + 12);
  thisMonthStart.setHours(9, 0, 0, 0);

  const trainingStart = new Date(now);
  trainingStart.setDate(trainingStart.getDate() + 16);
  trainingStart.setHours(10, 0, 0, 0);

  const sampleStart = new Date(now);
  sampleStart.setDate(sampleStart.getDate() + 28);
  sampleStart.setHours(18, 30, 0, 0);

  const campStart = new Date(now);
  campStart.setDate(campStart.getDate() + 42);
  campStart.setHours(13, 0, 0, 0);

  const fundraiserStart = new Date(now);
  fundraiserStart.setDate(fundraiserStart.getDate() + 75);
  fundraiserStart.setHours(17, 30, 0, 0);

  const pastStart = new Date(now);
  pastStart.setDate(pastStart.getDate() - 10);
  pastStart.setHours(10, 0, 0, 0);

  return {
    version: 4,
    initialized: false,
    users: [
      {
        id: "usr_admin",
        firstName: "Avery",
        lastName: "Bostwick",
        email: "avery@emergeministry.test",
        role: "admin"
      },
      {
        id: "usr_leader",
        firstName: "Jordan",
        lastName: "Reed",
        email: "jordan@emergeministry.test",
        role: "leader"
      },
      {
        id: "usr_student_placeholder",
        firstName: "Student",
        lastName: "Placeholder",
        email: "student@emergeministry.test",
        role: "student"
      },
      {
        id: "usr_parent_placeholder",
        firstName: "Parent",
        lastName: "Placeholder",
        email: "parent@emergeministry.test",
        role: "parent"
      }
    ],
    events: [
      {
        id: "evt_midweek_hangout",
        title: "Midweek Hangout",
        description: "A low-lift gathering for students to connect, worship, and hear a short teaching.",
        type: "weekly",
        startTime: thisWeekStart.toISOString(),
        endTime: addDays(thisWeekStart.toISOString(), 0),
        status: "planning",
        location: "Student Center",
        budgetTarget: 600,
        contactOwnerId: "usr_leader",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "Check whether small group leaders can rotate greeting and cleanup roles.",
        createdAt: now.toISOString()
      },
      {
        id: "evt_friday_night",
        title: "Friday Night",
        description: "A Friday gathering for students with games, worship, and a short leader announcement.",
        type: "weekly",
        startTime: fridayStart.toISOString(),
        endTime: addDays(fridayStart.toISOString(), 0),
        status: "planning",
        location: "Student Center",
        budgetTarget: 750,
        contactOwnerId: "usr_leader",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "",
        createdAt: now.toISOString()
      },
      {
        id: "evt_service_day",
        title: "High School Event",
        description: "High school students and leaders serve a local ministry partner with cleanup and care projects.",
        type: "service",
        startTime: thisMonthStart.toISOString(),
        endTime: addDays(thisMonthStart.toISOString(), 0),
        status: "planning",
        location: "Hope Center",
        budgetTarget: 1200,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "",
        createdAt: now.toISOString()
      },
      {
        id: "evt_volunteer_training",
        title: "Volunteer Training",
        description: "Leader onboarding and safety training for the fall student ministry season.",
        type: "service",
        startTime: trainingStart.toISOString(),
        endTime: addDays(trainingStart.toISOString(), 0),
        status: "planning",
        location: "Conference Room A",
        budgetTarget: 400,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "Confirm whether returning volunteers need a shorter refresher track.",
        createdAt: now.toISOString()
      },
      {
        id: "evt_winter_retreat",
        title: "Winter Retreat",
        description: "A weekend retreat for worship, teaching, small groups, and student connection.",
        type: "retreat",
        startTime: sampleStart.toISOString(),
        endTime: addDays(sampleStart.toISOString(), 2),
        status: "planning",
        location: "Lakeview Retreat Center",
        budgetTarget: 8500,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "Venue deposit is recorded. Parent communication still needs final packing details.",
        createdAt: now.toISOString()
      },
      {
        id: "evt_summer_camp",
        title: "Summer Camp",
        description: "A high-visibility camp event with registration, packing, volunteers, parent updates, and files to coordinate.",
        type: "camp",
        startTime: campStart.toISOString(),
        endTime: addDays(campStart.toISOString(), 4),
        status: "planning",
        location: "Camp Evergreen",
        budgetTarget: 18000,
        registrationDeadline: addDays(campStart.toISOString(), -21),
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "",
        createdAt: now.toISOString()
      },
      {
        id: "evt_fall_fundraiser",
        title: "Fall Fundraiser",
        description: "A student ministry fundraiser dinner and auction supporting retreats, camp scholarships, and outreach.",
        type: "service",
        startTime: fundraiserStart.toISOString(),
        endTime: addDays(fundraiserStart.toISOString(), 0),
        status: "planning",
        location: "Fellowship Hall",
        budgetTarget: 2500,
        contactOwnerId: "usr_leader",
        autoGeneratedTimeline: [],
        googleDriveFolderId: undefined,
        proPresenterPlaylistId: undefined,
        notes: "",
        createdAt: now.toISOString()
      },
      {
        id: "evt_parent_briefing",
        title: "Spring Parent Briefing",
        description: "A completed parent information meeting kept visible for Past Events grouping.",
        type: "weekly",
        startTime: pastStart.toISOString(),
        endTime: addDays(pastStart.toISOString(), 0),
        status: "ready",
        location: "Student Center",
        budgetTarget: 250,
        contactOwnerId: "usr_admin",
        autoGeneratedTimeline: [],
        googleDriveFolderId: "stub-drive-evt_parent_briefing",
        proPresenterPlaylistId: undefined,
        notes: "Past event retained for planning comparison.",
        createdAt: pastStart.toISOString()
      }
    ],
    tasks: [],
    communications: [],
    integrationLogs: [],
    expenses: [
      {
        id: "exp_deposit",
        eventId: "evt_winter_retreat",
        categoryId: "cat_venue",
        amount: 1500,
        description: "Venue deposit",
        timestamp: now.toISOString()
      }
    ],
    activity: []
  };
}

const globalStore = globalThis as typeof globalThis & {
  __emergeMvpStore?: MockStoreState;
};

const store = globalStore.__emergeMvpStore?.version === 4 ? globalStore.__emergeMvpStore : createInitialStore();
globalStore.__emergeMvpStore = store;

const { users, events, tasks, communications, integrationLogs, expenses, activity } = store;

function actorId() {
  return "usr_admin";
}

function recordActivity(input: Omit<ActivityLog, "id" | "actorId" | "timestamp">) {
  const item: ActivityLog = {
    id: uid("act"),
    actorId: actorId(),
    timestamp: new Date().toISOString(),
    ...input
  };
  activity.unshift(item);
  return item;
}

function generateTasksForEvent(event: MinistryEvent) {
  const templateTasks = defaultTemplateTasks[event.type];
  const generated = templateTasks.map((template) => {
    const assignee = users.find((user) => user.role === template.roleAssigned) ?? users[0];
    const task: ActiveTask = {
      id: `task_${event.id}_${template.id}`,
      eventId: event.id,
      taskTitle: template.taskTitle,
      dueDate: addDays(event.startTime, template.timelineOffsetDays),
      assignedUserId: assignee.id,
      status: "todo",
      autoGenerated: true,
      timelineOffsetDays: template.timelineOffsetDays
    };
    tasks.push(task);
    recordActivity({
      type: "task_generated",
      eventId: event.id,
      taskId: task.id,
      message: `Generated task: ${task.taskTitle}`,
      metadata: {
        dueDate: task.dueDate,
        timelineOffsetDays: task.timelineOffsetDays
      }
    });
    return task;
  });

  event.autoGeneratedTimeline = generated.map((task) => task.id);
  return generated;
}

if (!store.initialized) {
  events.forEach((event) => {
    generateTasksForEvent(event);
    recordActivity({
      type: "event_created",
      eventId: event.id,
      message: `Created event: ${event.title}`,
      metadata: { type: event.type }
    });
  });
  store.initialized = true;
}

export function listUsers() {
  return users;
}

export function listEvents() {
  return events;
}

export function getEvent(id: string) {
  return events.find((event) => event.id === id);
}

export function listTasks() {
  return tasks;
}

export function listActivity() {
  return activity;
}

export function listExpenses() {
  return expenses;
}

export function createEvent(input: {
  title: string;
  description: string;
  type: EventType;
  startTime: string;
  endTime: string;
  location?: string;
  targetGroup?: string;
  budgetTarget?: number;
  budgetActual?: number;
  volunteersNeeded?: number;
  priority?: string;
  contactOwnerId?: string;
}) {
  const event: MinistryEvent = {
    id: uid("evt"),
    title: input.title,
    description: input.description,
    type: input.type,
    startTime: input.startTime,
    endTime: input.endTime,
    status: "planning",
    location: input.location || undefined,
    targetGroup: input.targetGroup || undefined,
    budgetTarget: input.budgetTarget,
    budgetActual: input.budgetActual ?? 0,
    volunteersNeeded: input.volunteersNeeded,
    priority: input.priority || "normal",
    contactOwnerId: input.contactOwnerId,
    autoGeneratedTimeline: [],
    createdAt: new Date().toISOString()
  };

  events.unshift(event);
  recordActivity({
    type: "event_created",
    eventId: event.id,
    message: `Created event: ${event.title}`,
    metadata: { type: event.type }
  });
  generateTasksForEvent(event);
  return getWorkspace(event.id);
}

export function createTask(input: {
  eventId: string;
  taskTitle: string;
  dueDate: string;
  assignedUserId: string;
  status?: TaskStatus;
}) {
  const task: ActiveTask = {
    id: uid("task"),
    eventId: input.eventId,
    taskTitle: input.taskTitle,
    dueDate: input.dueDate,
    assignedUserId: input.assignedUserId,
    status: input.status ?? "todo",
    autoGenerated: false,
    timelineOffsetDays: 0
  };
  tasks.push(task);
  recordActivity({
    type: "task_generated",
    eventId: input.eventId,
    taskId: task.id,
    message: `Added task: ${task.taskTitle}`,
    metadata: {}
  });
  return task;
}

export function updateEvent(
  id: string,
  input: Partial<
    Pick<MinistryEvent, "title" | "description" | "startTime" | "endTime" | "location" | "targetGroup" | "budgetTarget" | "budgetActual" | "volunteersNeeded" | "priority" | "contactOwnerId" | "notes">
  >
) {
  const event = getEvent(id);
  if (!event) return undefined;

  const changedFields: string[] = [];

  (["title", "description", "startTime", "endTime", "location", "targetGroup", "budgetTarget", "budgetActual", "volunteersNeeded", "priority", "contactOwnerId", "notes"] as const).forEach((field) => {
    if (input[field] !== undefined && input[field] !== event[field]) {
      changedFields.push(field);
    }
  });

  Object.assign(event, input);

  if (changedFields.length > 0) {
    recordActivity({
      type: input.notes !== undefined ? "event_notes_updated" : "event_updated",
      eventId: event.id,
      message: input.notes !== undefined ? `Updated event notes: ${event.title}` : `Updated event information: ${event.title}`,
      metadata: { fields: changedFields.join(", ") }
    });
  }

  return getWorkspace(event.id);
}

export function updateTask(
  id: string,
  input: Partial<Pick<ActiveTask, "taskTitle" | "dueDate" | "assignedUserId" | "status" | "notes">>
) {
  const task = tasks.find((item) => item.id === id);
  if (!task) return undefined;

  const previousStatus = task.status;
  const previousOwner = task.assignedUserId;
  const previousTitle = task.taskTitle;
  const previousDueDate = task.dueDate;
  const previousNotes = task.notes;

  Object.assign(task, input);

  if (input.status && input.status !== previousStatus) {
    recordActivity({
      type: "task_status_changed",
      eventId: task.eventId,
      taskId: task.id,
      message: `Moved task to ${input.status.replace("_", " ")}: ${task.taskTitle}`,
      metadata: { from: previousStatus, to: input.status }
    });
  }

  if (input.assignedUserId && input.assignedUserId !== previousOwner) {
    recordActivity({
      type: "task_owner_changed",
      eventId: task.eventId,
      taskId: task.id,
      message: `Changed owner for task: ${task.taskTitle}`,
      metadata: { from: previousOwner, to: input.assignedUserId }
    });
  }

  if (input.taskTitle && input.taskTitle !== previousTitle) {
    recordActivity({
      type: "task_edited",
      eventId: task.eventId,
      taskId: task.id,
      message: `Edited task title: ${input.taskTitle}`,
      metadata: { from: previousTitle, to: input.taskTitle }
    });
  }

  if (input.dueDate && input.dueDate !== previousDueDate) {
    recordActivity({
      type: "task_edited",
      eventId: task.eventId,
      taskId: task.id,
      message: `Changed due date for task: ${task.taskTitle}`,
      metadata: { from: previousDueDate, to: input.dueDate }
    });
  }

  if (input.notes !== undefined && input.notes !== previousNotes) {
    recordActivity({
      type: "task_notes_updated",
      eventId: task.eventId,
      taskId: task.id,
      message: `Updated task notes: ${task.taskTitle}`,
      metadata: { hasNotes: Boolean(input.notes?.trim()) }
    });
  }

  return task;
}

export function generateCommunicationPreview(eventId: string) {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const eventTasks = tasks.filter((task) => task.eventId === eventId);
  const openTasks = eventTasks.filter((task) => task.status !== "done");
  const missing = getMissingInformation(event, expenses.filter((expense) => expense.eventId === eventId));
  const missingNote = missing.length
    ? `Details still being confirmed: ${missing.map((item) => item.label).join(" ")}`
    : "All core event information is ready for review.";
  const locationLine = event.location ?? "Location is still being finalized.";
  const dateLine = new Date(event.startTime).toLocaleString();
  const taskLine = `${openTasks.length} open task${openTasks.length === 1 ? "" : "s"} remain before this event is ready.`;
  const budgetLine = event.budgetTarget ? `Budget target: $${event.budgetTarget.toLocaleString()}.` : "Budget target is still being confirmed.";
  const registrationLine = "Registration details are still being confirmed.";
  const packingLine =
    event.type === "retreat" || event.type === "camp"
      ? "Packing list is not available yet."
      : "Packing list is not needed for this event type in MVP 1.";

  const createdAt = new Date().toISOString();
  const previews: CommunicationPackage[] = [
    {
      id: uid("comm"),
      eventId,
      type: "parent_email",
      payload: {
        subject: `Parent email preview: ${event.title}`,
        body: `Preview only — not sent.\n\nHi families,\n\nHere is the current preview for ${event.title}, a ${event.type} event.\n\nSummary: ${event.description || "Event summary is still being finalized."}\nDate/time: ${dateLine}\nLocation: ${locationLine}\n${registrationLine}\n${packingLine}\nWhat families need to know: ${missingNote}\n${budgetLine}\nNext step: Watch for the final details from the ministry team before making plans.`
      },
      status: "preview",
      createdAt
    },
    {
      id: uid("comm"),
      eventId,
      type: "leader_brief",
      payload: {
        subject: `Leader announcement preview: ${event.title}`,
        body: `Preview only — not sent.\n\nLeader heads up for ${event.title}: ${event.description || "Event summary is still being finalized."}\n\nDate/time: ${dateLine}\nLocation: ${locationLine}\nVolunteer/task awareness: ${taskLine}\nMissing info: ${missingNote}\n${registrationLine}\nNext step for leaders: Review your assigned tasks and flag anything blocked.`
      },
      status: "preview",
      createdAt
    },
    {
      id: uid("comm"),
      eventId,
      type: "student_announcement",
      payload: {
        subject: `Blast text preview: ${event.title}`,
        body: `Preview only — not sent.\n\n${event.title}: ${dateLine}. ${event.location ? `Meet at ${event.location}.` : "Location is still being finalized."} ${missing.length ? "More details coming soon." : "Watch for final reminders soon."}`
      },
      status: "preview",
      createdAt
    }
  ];

  communications.unshift(...previews);
  recordActivity({
    type: "communication_preview_generated",
    eventId,
    message: `Generated communication previews for ${event.title}`,
    metadata: { previewCount: previews.length, sent: false }
  });
  return previews;
}

export function runIntegrationStub(eventId: string, type: "google_drive" | "propresenter" | "google_calendar" | "planning_center") {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const log = integrationAdapters[type].runStubAction(event);
  integrationLogs.unshift(log);

  if (type === "google_drive") {
    event.googleDriveFolderId = `stub-drive-${event.id}`;
  }

  if (type === "propresenter") {
    event.proPresenterPlaylistId = `stub-pro-${event.id}`;
  }

  recordActivity({
    type: "integration_stub_action",
    eventId,
    message: `Stub Mode: ${log.details.action} for ${event.title}`,
    metadata: { integrationType: type, status: log.status }
  });

  return log;
}

export function getBudget(eventId: string) {
  const event = getEvent(eventId);
  const eventExpenses = expenses.filter((expense) => expense.eventId === eventId);
  const spent = eventExpenses.reduce((sum, expense) => sum + expense.amount, 0);
  return {
    eventId,
    target: event?.budgetTarget ?? 0,
    spent,
    remaining: (event?.budgetTarget ?? 0) - spent,
    expenses: eventExpenses
  };
}

export function addExpense(input: { eventId: string; categoryId: string; amount: number; description: string }) {
  const expense: EventExpense = {
    id: uid("exp"),
    timestamp: new Date().toISOString(),
    ...input
  };
  expenses.unshift(expense);
  return expense;
}

export function getWorkspace(eventId: string): EventWorkspace | undefined {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const eventExpenses = expenses.filter((expense) => expense.eventId === eventId);

  return {
    event,
    tasks: tasks.filter((task) => task.eventId === eventId),
    communications: communications.filter((item) => item.eventId === eventId),
    integrationLogs: integrationLogs.filter((log) => log.eventId === eventId),
    expenses: eventExpenses,
    missingInformation: getMissingInformation(event, eventExpenses),
    activity: activity.filter((item) => item.eventId === eventId)
  };
}

export const taskStatuses: TaskStatus[] = ["todo", "in_progress", "blocked", "done"];
