import { integrationAdapters } from "./adapters/integrations";
import { getMissingInformation } from "./missing-info";
import { defaultTemplateTasks } from "./templates";
import type {
  ActiveTask,
  ActivityLog,
  CommunicationPackage,
  EventExpense,
  EventType,
  EventWorkspace,
  IntegrationSyncLog,
  MinistryEvent,
  TaskStatus,
  User
} from "./types";
import { addDays, uid } from "./utils";

const now = new Date();
const sampleStart = new Date(now);
sampleStart.setDate(sampleStart.getDate() + 28);
sampleStart.setHours(18, 30, 0, 0);

const users: User[] = [
  {
    id: "usr_admin",
    firstName: "Avery",
    lastName: "Bostwick",
    email: "avery@emergeministry.test",
    role: "admin"
  },
  {
    id: "usr_leader",
    firstName: "Jordan",
    lastName: "Reed",
    email: "jordan@emergeministry.test",
    role: "leader"
  },
  {
    id: "usr_student_placeholder",
    firstName: "Student",
    lastName: "Placeholder",
    email: "student@emergeministry.test",
    role: "student"
  },
  {
    id: "usr_parent_placeholder",
    firstName: "Parent",
    lastName: "Placeholder",
    email: "parent@emergeministry.test",
    role: "parent"
  }
];

const events: MinistryEvent[] = [
  {
    id: "evt_winter_retreat",
    title: "Winter Retreat",
    description: "A weekend retreat for worship, teaching, small groups, and student connection.",
    type: "retreat",
    startTime: sampleStart.toISOString(),
    endTime: addDays(sampleStart.toISOString(), 2),
    status: "planning",
    location: "Lakeview Retreat Center",
    budgetTarget: 8500,
    contactOwnerId: "usr_admin",
    autoGeneratedTimeline: [],
    googleDriveFolderId: undefined,
    proPresenterPlaylistId: undefined,
    createdAt: now.toISOString()
  }
];

const tasks: ActiveTask[] = [];
const communications: CommunicationPackage[] = [];
const integrationLogs: IntegrationSyncLog[] = [];
const expenses: EventExpense[] = [
  {
    id: "exp_deposit",
    eventId: "evt_winter_retreat",
    categoryId: "cat_venue",
    amount: 1500,
    description: "Venue deposit",
    timestamp: now.toISOString()
  }
];
const activity: ActivityLog[] = [];

function actorId() {
  return "usr_admin";
}

function recordActivity(input: Omit<ActivityLog, "id" | "actorId" | "timestamp">) {
  const item: ActivityLog = {
    id: uid("act"),
    actorId: actorId(),
    timestamp: new Date().toISOString(),
    ...input
  };
  activity.unshift(item);
  return item;
}

function generateTasksForEvent(event: MinistryEvent) {
  const templateTasks = defaultTemplateTasks[event.type];
  const generated = templateTasks.map((template) => {
    const assignee = users.find((user) => user.role === template.roleAssigned) ?? users[0];
    const task: ActiveTask = {
      id: uid("task"),
      eventId: event.id,
      taskTitle: template.taskTitle,
      dueDate: addDays(event.startTime, template.timelineOffsetDays),
      assignedUserId: assignee.id,
      status: "todo",
      autoGenerated: true,
      timelineOffsetDays: template.timelineOffsetDays
    };
    tasks.push(task);
    recordActivity({
      type: "task_generated",
      eventId: event.id,
      taskId: task.id,
      message: `Generated task: ${task.taskTitle}`,
      metadata: {
        dueDate: task.dueDate,
        timelineOffsetDays: task.timelineOffsetDays
      }
    });
    return task;
  });

  event.autoGeneratedTimeline = generated.map((task) => task.id);
  return generated;
}

generateTasksForEvent(events[0]);
recordActivity({
  type: "event_created",
  eventId: events[0].id,
  message: `Created event: ${events[0].title}`,
  metadata: { type: events[0].type }
});

export function listUsers() {
  return users;
}

export function listEvents() {
  return events;
}

export function getEvent(id: string) {
  return events.find((event) => event.id === id);
}

export function listTasks() {
  return tasks;
}

export function listActivity() {
  return activity;
}

export function createEvent(input: {
  title: string;
  description: string;
  type: EventType;
  startTime: string;
  endTime: string;
  location?: string;
  budgetTarget?: number;
  contactOwnerId?: string;
}) {
  const event: MinistryEvent = {
    id: uid("evt"),
    title: input.title,
    description: input.description,
    type: input.type,
    startTime: input.startTime,
    endTime: input.endTime,
    status: "planning",
    location: input.location || undefined,
    budgetTarget: input.budgetTarget,
    contactOwnerId: input.contactOwnerId,
    autoGeneratedTimeline: [],
    createdAt: new Date().toISOString()
  };

  events.unshift(event);
  recordActivity({
    type: "event_created",
    eventId: event.id,
    message: `Created event: ${event.title}`,
    metadata: { type: event.type }
  });
  generateTasksForEvent(event);
  return getWorkspace(event.id);
}

export function updateEvent(
  id: string,
  input: Partial<Pick<MinistryEvent, "title" | "description" | "startTime" | "endTime" | "location" | "budgetTarget" | "contactOwnerId">>
) {
  const event = getEvent(id);
  if (!event) return undefined;

  const changedFields: string[] = [];

  (["title", "description", "startTime", "endTime", "location", "budgetTarget", "contactOwnerId"] as const).forEach((field) => {
    if (input[field] !== undefined && input[field] !== event[field]) {
      changedFields.push(field);
    }
  });

  Object.assign(event, input);

  if (changedFields.length > 0) {
    recordActivity({
      type: "event_updated",
      eventId: event.id,
      message: `Updated event details: ${event.title}`,
      metadata: { fields: changedFields.join(", ") }
    });
  }

  return getWorkspace(event.id);
}

export function updateTask(
  id: string,
  input: Partial<Pick<ActiveTask, "taskTitle" | "dueDate" | "assignedUserId" | "status">>
) {
  const task = tasks.find((item) => item.id === id);
  if (!task) return undefined;

  const previousStatus = task.status;
  const previousOwner = task.assignedUserId;
  const previousTitle = task.taskTitle;
  const previousDueDate = task.dueDate;

  Object.assign(task, input);

  if (input.status && input.status !== previousStatus) {
    recordActivity({
      type: "task_status_changed",
      eventId: task.eventId,
      taskId: task.id,
      message: `Moved task to ${input.status.replace("_", " ")}: ${task.taskTitle}`,
      metadata: { from: previousStatus, to: input.status }
    });
  }

  if (input.assignedUserId && input.assignedUserId !== previousOwner) {
    recordActivity({
      type: "task_owner_changed",
      eventId: task.eventId,
      taskId: task.id,
      message: `Changed owner for task: ${task.taskTitle}`,
      metadata: { from: previousOwner, to: input.assignedUserId }
    });
  }

  if (input.taskTitle && input.taskTitle !== previousTitle) {
    recordActivity({
      type: "task_edited",
      eventId: task.eventId,
      taskId: task.id,
      message: `Edited task title: ${input.taskTitle}`,
      metadata: { from: previousTitle, to: input.taskTitle }
    });
  }

  if (input.dueDate && input.dueDate !== previousDueDate) {
    recordActivity({
      type: "task_edited",
      eventId: task.eventId,
      taskId: task.id,
      message: `Changed due date for task: ${task.taskTitle}`,
      metadata: { from: previousDueDate, to: input.dueDate }
    });
  }

  return task;
}

export function generateCommunicationPreview(eventId: string) {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const item: CommunicationPackage = {
    id: uid("comm"),
    eventId,
    type: "parent_email",
    payload: {
      subject: `${event.title} details for families`,
      body: `Preview only: ${event.title} is scheduled for ${new Date(event.startTime).toLocaleDateString()}. This communication is not sent in MVP 1.`
    },
    status: "preview",
    createdAt: new Date().toISOString()
  };

  communications.unshift(item);
  recordActivity({
    type: "communication_preview_generated",
    eventId,
    message: `Generated communication preview for ${event.title}`,
    metadata: { communicationId: item.id, sent: false }
  });
  return item;
}

export function runIntegrationStub(eventId: string, type: "google_drive" | "propresenter" | "google_calendar" | "planning_center") {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const log = integrationAdapters[type].runStubAction(event);
  integrationLogs.unshift(log);

  if (type === "google_drive") {
    event.googleDriveFolderId = `stub-drive-${event.id}`;
  }

  if (type === "propresenter") {
    event.proPresenterPlaylistId = `stub-pro-${event.id}`;
  }

  recordActivity({
    type: "integration_stub_action",
    eventId,
    message: `Stub Mode: ${log.details.action} for ${event.title}`,
    metadata: { integrationType: type, status: log.status }
  });

  return log;
}

export function getBudget(eventId: string) {
  const event = getEvent(eventId);
  const eventExpenses = expenses.filter((expense) => expense.eventId === eventId);
  const spent = eventExpenses.reduce((sum, expense) => sum + expense.amount, 0);
  return {
    eventId,
    target: event?.budgetTarget ?? 0,
    spent,
    remaining: (event?.budgetTarget ?? 0) - spent,
    expenses: eventExpenses
  };
}

export function addExpense(input: { eventId: string; categoryId: string; amount: number; description: string }) {
  const expense: EventExpense = {
    id: uid("exp"),
    timestamp: new Date().toISOString(),
    ...input
  };
  expenses.unshift(expense);
  return expense;
}

export function getWorkspace(eventId: string): EventWorkspace | undefined {
  const event = getEvent(eventId);
  if (!event) return undefined;

  const eventExpenses = expenses.filter((expense) => expense.eventId === eventId);

  return {
    event,
    tasks: tasks.filter((task) => task.eventId === eventId),
    communications: communications.filter((item) => item.eventId === eventId),
    integrationLogs: integrationLogs.filter((log) => log.eventId === eventId),
    expenses: eventExpenses,
    missingInformation: getMissingInformation(event, eventExpenses),
    activity: activity.filter((item) => item.eventId === eventId)
  };
}

export const taskStatuses: TaskStatus[] = ["todo", "in_progress", "blocked", "done"];
