export type Role = "admin" | "leader" | "student" | "parent";

export type EventStatus = "draft" | "planning" | "ready" | "not_started" | "in_progress" | "working_on_it" | "stuck" | "completed";

export type EventType =
  | "sunday_morning_service"
  | "sunday_evening_service"
  | "middle_school_event"
  | "high_school_event"
  | "small_group_gathering"
  | "missions_trip"
  | "conference"
  | "combined_event"
  | "other";

export type TaskStatus = "todo" | "in_progress" | "blocked" | "done";

export type ActivityType =
  | "event_created"
  | "event_updated"
  | "task_generated"
  | "task_status_changed"
  | "task_owner_changed"
  | "task_edited"
  | "event_notes_updated"
  | "task_notes_updated"
  | "communication_preview_generated"
  | "integration_stub_action";

export type IntegrationType = "planning_center" | "google_calendar" | "google_drive" | "propresenter";

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  role: Role;
  grade?: string;
  ministryId?: string;
}

export interface MinistryEvent {
  id: string;
  ministryId?: string;
  title: string;
  description: string;
  type: EventType;
  startTime: string;
  endTime: string;
  status: EventStatus;
  location?: string;
  targetGroup?: string;
  budgetTarget?: number;
  budgetActual?: number;
  volunteersNeeded?: number;
  priority?: string;
  registrationDeadline?: string;
  contactOwnerId?: string;
  assignedLeaderIds?: string[];
  autoGeneratedTimeline: string[];
  googleDriveFolderId?: string;
  proPresenterPlaylistId?: string;
  notes?: string;
  archivedAt?: string | null;
  archivedByUserId?: string | null;
  archiveReason?: string | null;
  createdAt: string;
}

export interface TemplateTask {
  id: string;
  taskTitle: string;
  timelineOffsetDays: number;
  roleAssigned: "admin" | "leader";
}

export interface ActiveTask {
  id: string;
  ministryId?: string;
  eventId: string;
  taskTitle: string;
  dueDate: string;
  assignedUserId: string;
  status: TaskStatus;
  autoGenerated: boolean;
  timelineOffsetDays: number;
  notes?: string;
}

export interface CommunicationPackage {
  id: string;
  eventId: string;
  type: "parent_email" | "leader_brief" | "student_announcement";
  payload: {
    subject: string;
    body: string;
  };
  scheduledTime?: string;
  status: "preview";
  createdAt: string;
}

export interface IntegrationSyncLog {
  id: string;
  integrationType: IntegrationType;
  eventId: string;
  status: "stub_mode";
  details: {
    action: string;
    message: string;
  };
  timestamp: string;
}

export interface BudgetCategory {
  id: string;
  name: string;
  description: string;
}

export interface EventExpense {
  id: string;
  eventId: string;
  categoryId: string;
  amount: number;
  description: string;
  timestamp: string;
}

export interface ActivityLog {
  id: string;
  ministryId?: string;
  type: ActivityType;
  eventId?: string;
  taskId?: string;
  actorId: string;
  message: string;
  metadata: Record<string, string | number | boolean | null>;
  timestamp: string;
}

export interface MissingInformationItem {
  id: string;
  area: "communications" | "drive" | "budget" | "calendar";
  label: string;
  severity: "required" | "recommended";
}

export interface EventWorkspace {
  event: MinistryEvent;
  tasks: ActiveTask[];
  communications: CommunicationPackage[];
  integrationLogs: IntegrationSyncLog[];
  expenses: EventExpense[];
  missingInformation: MissingInformationItem[];
  activity: ActivityLog[];
}
