import { describe, expect, it } from "vitest";
import { deriveEventStatusFromTasks } from "@/lib/ministry/event-status";
import type { ActiveTask } from "@/lib/types";

function task(status: ActiveTask["status"]): ActiveTask {
  return {
    id: `task-${status}-${Math.random()}`,
    eventId: "event-1",
    taskTitle: status,
    dueDate: "2026-07-20T12:00:00.000Z",
    assignedUserId: "user-1",
    status,
    autoGenerated: false,
    timelineOffsetDays: 0
  };
}

describe("event status derivation", () => {
  it("derives parent event status from child task status", () => {
    expect(deriveEventStatusFromTasks([])).toBeNull();
    expect(deriveEventStatusFromTasks([task("todo"), task("todo")])).toBe("planning");
    expect(deriveEventStatusFromTasks([task("todo"), task("in_progress")])).toBe("working_on_it");
    expect(deriveEventStatusFromTasks([task("done"), task("done")])).toBe("ready");
    expect(deriveEventStatusFromTasks([task("done"), task("blocked")])).toBe("stuck");
  });
});
