import { describe, expect, it } from "vitest";

import { buildMinistryMemoryDemo } from "@/lib/ministry/organizational-memory";
import type { MinistryOverview } from "@/lib/data/ministry-repository";
import type { MinistryEvent } from "@/lib/types";

const baseEvent: MinistryEvent = {
  id: "event-current",
  title: "Fall Retreat Demo",
  description: "Current retreat",
  type: "conference",
  startTime: "2026-10-02T18:00:00.000Z",
  endTime: "2026-10-04T18:00:00.000Z",
  status: "planning",
  autoGeneratedTimeline: [],
  createdAt: "2026-07-01T12:00:00.000Z"
};

describe("buildMinistryMemoryDemo", () => {
  it("summarizes historical public demo records without implying live sync", () => {
    const overview: MinistryOverview = {
      events: [
        {
          ...baseEvent,
          id: "retreat-2021",
          title: "Fall Retreat 2021",
          startTime: "2021-10-01T18:00:00.000Z",
          endTime: "2021-10-03T18:00:00.000Z",
          status: "completed",
          archivedAt: "2021-10-17T18:00:00.000Z",
          googleImportStatus: "imported_from_google",
          googleCalendarEventId: "guest-calendar-retreat-2021",
          googleDriveFolderId: "guest-drive-retreat-2021",
          proPresenterPlaylistId: "guest-pro-retreat-2021"
        },
        {
          ...baseEvent,
          id: "serve-2024",
          title: "City Serve Saturday 2024",
          type: "missions_trip",
          startTime: "2024-04-27T14:00:00.000Z",
          endTime: "2024-04-27T20:00:00.000Z",
          status: "completed",
          archivedAt: "2024-05-11T20:00:00.000Z",
          googleImportStatus: "imported_from_google",
          googleCalendarEventId: "guest-calendar-serve-2024",
          googleDriveFolderId: "guest-drive-serve-2024"
        },
        baseEvent
      ],
      tasks: [
        {
          id: "task-follow-up",
          eventId: "retreat-2021",
          taskTitle: "Save Drive debrief and follow-up notes",
          dueDate: "2021-10-05T12:00:00.000Z",
          assignedUserId: "user-1",
          status: "done",
          autoGenerated: true,
          timelineOffsetDays: 2
        }
      ],
      users: [],
      expenses: [
        {
          id: "expense-1",
          eventId: "retreat-2021",
          categoryId: "lodging",
          amount: 5000,
          description: "Archived actual",
          timestamp: "2021-10-05T12:00:00.000Z"
        }
      ],
      activity: []
    };

    const memory = buildMinistryMemoryDemo(overview, new Date("2026-07-27T12:00:00.000Z"));

    expect(memory.yearSpanLabel).toBe("2021-2026");
    expect(memory.historicalEventCount).toBe(2);
    expect(memory.currentEventCount).toBe(1);
    expect(memory.stubSourceCount).toBe(7);
    expect(memory.sources.find((source) => source.label === "Planning Center attendance snapshots")?.detail).toContain("Not connected");
    expect(memory.prompts).toContain("Compare this year's retreat plan with the last four retreats.");
  });
});
