import { describe, expect, it } from "vitest";

import { buildMinistryDecisionCenterState } from "@/lib/decision-center/ministry";
import type { MinistryOverview } from "@/lib/data/ministry-repository";

const now = new Date("2026-07-25T12:00:00.000Z");

describe("buildMinistryDecisionCenterState", () => {
  it("derives evidence-linked ministry signals from existing overview data", () => {
    const state = buildMinistryDecisionCenterState(
      overview({
        events: [
          {
            id: "evt_1",
            title: "Fall Kickoff",
            description: "",
            type: "middle_school_event",
            startTime: "2026-08-01T18:00:00.000Z",
            endTime: "2026-08-01T20:00:00.000Z",
            status: "planning",
            budgetTarget: 500,
            budgetActual: 650,
            autoGeneratedTimeline: [],
            createdAt: "2026-07-20T12:00:00.000Z"
          }
        ],
        tasks: [
          {
            id: "task_1",
            eventId: "evt_1",
            taskTitle: "Confirm leader huddle",
            dueDate: "2026-07-30T12:00:00.000Z",
            assignedUserId: "usr_1",
            status: "blocked",
            autoGenerated: true,
            timelineOffsetDays: -7
          }
        ]
      }),
      now
    );

    expect(state.metrics.find((metric) => metric.id === "readiness")?.value).toBe("1");
    expect(state.signals.map((signal) => signal.id)).toEqual(
      expect.arrayContaining([
        "ministry.event-readiness-gaps",
        "ministry.task-load",
        "ministry.communication-ownership",
        "ministry.budget-pressure",
        "ministry.judged-scripture-flow"
      ])
    );
    expect(state.signals.find((signal) => signal.id === "ministry.event-readiness-gaps")?.evidence[0]).toMatchObject({
      sourceKind: "event",
      label: "Fall Kickoff"
    });
    expect(state.attention[0]?.nextStepHref).toBe("/events");
  });

  it("keeps YouVersion and Gloo as explicit judged integration flows", () => {
    const state = buildMinistryDecisionCenterState(overview(), now);

    expect(state.judgedIntegrationFlows.map((flow) => flow.id)).toEqual([
      "youversion",
      "gloo-discussion",
      "gloo-reading-plan"
    ]);
    expect(state.judgedIntegrationFlows[0]).toMatchObject({
      provider: "YouVersion Platform API",
      visibleStep: "Scripture grounding"
    });
    expect(state.judgedIntegrationFlows[1]?.serverFlow).toContain("generateMeridianDiscussionDraft");
    expect(state.judgedIntegrationFlows[2]?.serverFlow).toContain("generateMeridianReadingPlanDraft");
  });
});

function overview(partial: Partial<MinistryOverview> = {}): MinistryOverview {
  return {
    events: [],
    tasks: [],
    users: [
      {
        id: "usr_1",
        firstName: "Alex",
        lastName: "Walker",
        email: "alex@example.test",
        role: "admin"
      }
    ],
    expenses: [],
    activity: [],
    ...partial
  };
}
